// Code generated by ent, DO NOT EDIT.

package proxyprobelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldID, id))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldProxyID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldSource, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldTarget, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldSuccess, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldLatencyMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldErrorMessage, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldIPAddress, v))
}

// CountryCode applies equality check predicate on the "country_code" field. It's identical to CountryCodeEQ.
func CountryCode(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCountryCode, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCountry, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldRegion, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCity, v))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCheckedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldProxyID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldSource, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldTarget, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldSuccess, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldLatencyMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// CountryCodeEQ applies the EQ predicate on the "country_code" field.
func CountryCodeEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCountryCode, v))
}

// CountryCodeNEQ applies the NEQ predicate on the "country_code" field.
func CountryCodeNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldCountryCode, v))
}

// CountryCodeIn applies the In predicate on the "country_code" field.
func CountryCodeIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldCountryCode, vs...))
}

// CountryCodeNotIn applies the NotIn predicate on the "country_code" field.
func CountryCodeNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldCountryCode, vs...))
}

// CountryCodeGT applies the GT predicate on the "country_code" field.
func CountryCodeGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldCountryCode, v))
}

// CountryCodeGTE applies the GTE predicate on the "country_code" field.
func CountryCodeGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldCountryCode, v))
}

// CountryCodeLT applies the LT predicate on the "country_code" field.
func CountryCodeLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldCountryCode, v))
}

// CountryCodeLTE applies the LTE predicate on the "country_code" field.
func CountryCodeLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldCountryCode, v))
}

// CountryCodeContains applies the Contains predicate on the "country_code" field.
func CountryCodeContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldCountryCode, v))
}

// CountryCodeHasPrefix applies the HasPrefix predicate on the "country_code" field.
func CountryCodeHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldCountryCode, v))
}

// CountryCodeHasSuffix applies the HasSuffix predicate on the "country_code" field.
func CountryCodeHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldCountryCode, v))
}

// CountryCodeIsNil applies the IsNil predicate on the "country_code" field.
func CountryCodeIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldCountryCode))
}

// CountryCodeNotNil applies the NotNil predicate on the "country_code" field.
func CountryCodeNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldCountryCode))
}

// CountryCodeEqualFold applies the EqualFold predicate on the "country_code" field.
func CountryCodeEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldCountryCode, v))
}

// CountryCodeContainsFold applies the ContainsFold predicate on the "country_code" field.
func CountryCodeContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldCountryCode, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldCountry))
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldCountry))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldCountry, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionIsNil applies the IsNil predicate on the "region" field.
func RegionIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldRegion))
}

// RegionNotNil applies the NotNil predicate on the "region" field.
func RegionNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldRegion))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldRegion, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldContainsFold(FieldCity, v))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldCheckedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyProbeLog) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyProbeLog) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyProbeLog) predicate.ProxyProbeLog {
	return predicate.ProxyProbeLog(sql.NotPredicates(p))
}
