// Code generated by ent, DO NOT EDIT.

package userriskprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userriskprofile type in the database.
	Label = "user_risk_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConsecutiveBadDays holds the string denoting the consecutive_bad_days field in the database.
	FieldConsecutiveBadDays = "consecutive_bad_days"
	// FieldLastEvaluatedAt holds the string denoting the last_evaluated_at field in the database.
	FieldLastEvaluatedAt = "last_evaluated_at"
	// FieldLastWarnedAt holds the string denoting the last_warned_at field in the database.
	FieldLastWarnedAt = "last_warned_at"
	// FieldGracePeriodStartedAt holds the string denoting the grace_period_started_at field in the database.
	FieldGracePeriodStartedAt = "grace_period_started_at"
	// FieldLockedAt holds the string denoting the locked_at field in the database.
	FieldLockedAt = "locked_at"
	// FieldLockReason holds the string denoting the lock_reason field in the database.
	FieldLockReason = "lock_reason"
	// FieldLastEvaluationSummary holds the string denoting the last_evaluation_summary field in the database.
	FieldLastEvaluationSummary = "last_evaluation_summary"
	// FieldExempted holds the string denoting the exempted field in the database.
	FieldExempted = "exempted"
	// FieldExemptedAt holds the string denoting the exempted_at field in the database.
	FieldExemptedAt = "exempted_at"
	// FieldExemptedBy holds the string denoting the exempted_by field in the database.
	FieldExemptedBy = "exempted_by"
	// FieldExemptionReason holds the string denoting the exemption_reason field in the database.
	FieldExemptionReason = "exemption_reason"
	// FieldUnlockedAt holds the string denoting the unlocked_at field in the database.
	FieldUnlockedAt = "unlocked_at"
	// FieldUnlockedBy holds the string denoting the unlocked_by field in the database.
	FieldUnlockedBy = "unlocked_by"
	// FieldUnlockReason holds the string denoting the unlock_reason field in the database.
	FieldUnlockReason = "unlock_reason"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userriskprofile in the database.
	Table = "user_risk_profiles"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_risk_profiles"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userriskprofile fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldScore,
	FieldStatus,
	FieldConsecutiveBadDays,
	FieldLastEvaluatedAt,
	FieldLastWarnedAt,
	FieldGracePeriodStartedAt,
	FieldLockedAt,
	FieldLockReason,
	FieldLastEvaluationSummary,
	FieldExempted,
	FieldExemptedAt,
	FieldExemptedBy,
	FieldExemptionReason,
	FieldUnlockedAt,
	FieldUnlockedBy,
	FieldUnlockReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultConsecutiveBadDays holds the default value on creation for the "consecutive_bad_days" field.
	DefaultConsecutiveBadDays int
	// DefaultLockReason holds the default value on creation for the "lock_reason" field.
	DefaultLockReason string
	// DefaultLastEvaluationSummary holds the default value on creation for the "last_evaluation_summary" field.
	DefaultLastEvaluationSummary string
	// DefaultExempted holds the default value on creation for the "exempted" field.
	DefaultExempted bool
	// DefaultExemptionReason holds the default value on creation for the "exemption_reason" field.
	DefaultExemptionReason string
	// DefaultUnlockReason holds the default value on creation for the "unlock_reason" field.
	DefaultUnlockReason string
)

// OrderOption defines the ordering options for the UserRiskProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConsecutiveBadDays orders the results by the consecutive_bad_days field.
func ByConsecutiveBadDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveBadDays, opts...).ToFunc()
}

// ByLastEvaluatedAt orders the results by the last_evaluated_at field.
func ByLastEvaluatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEvaluatedAt, opts...).ToFunc()
}

// ByLastWarnedAt orders the results by the last_warned_at field.
func ByLastWarnedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastWarnedAt, opts...).ToFunc()
}

// ByGracePeriodStartedAt orders the results by the grace_period_started_at field.
func ByGracePeriodStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGracePeriodStartedAt, opts...).ToFunc()
}

// ByLockedAt orders the results by the locked_at field.
func ByLockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedAt, opts...).ToFunc()
}

// ByLockReason orders the results by the lock_reason field.
func ByLockReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockReason, opts...).ToFunc()
}

// ByLastEvaluationSummary orders the results by the last_evaluation_summary field.
func ByLastEvaluationSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEvaluationSummary, opts...).ToFunc()
}

// ByExempted orders the results by the exempted field.
func ByExempted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExempted, opts...).ToFunc()
}

// ByExemptedAt orders the results by the exempted_at field.
func ByExemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExemptedAt, opts...).ToFunc()
}

// ByExemptedBy orders the results by the exempted_by field.
func ByExemptedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExemptedBy, opts...).ToFunc()
}

// ByExemptionReason orders the results by the exemption_reason field.
func ByExemptionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExemptionReason, opts...).ToFunc()
}

// ByUnlockedAt orders the results by the unlocked_at field.
func ByUnlockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlockedAt, opts...).ToFunc()
}

// ByUnlockedBy orders the results by the unlocked_by field.
func ByUnlockedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlockedBy, opts...).ToFunc()
}

// ByUnlockReason orders the results by the unlock_reason field.
func ByUnlockReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlockReason, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
