// Code generated by ent, DO NOT EDIT.

package userriskprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUserID, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldScore, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldStatus, v))
}

// ConsecutiveBadDays applies equality check predicate on the "consecutive_bad_days" field. It's identical to ConsecutiveBadDaysEQ.
func ConsecutiveBadDays(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldConsecutiveBadDays, v))
}

// LastEvaluatedAt applies equality check predicate on the "last_evaluated_at" field. It's identical to LastEvaluatedAtEQ.
func LastEvaluatedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastWarnedAt applies equality check predicate on the "last_warned_at" field. It's identical to LastWarnedAtEQ.
func LastWarnedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastWarnedAt, v))
}

// GracePeriodStartedAt applies equality check predicate on the "grace_period_started_at" field. It's identical to GracePeriodStartedAtEQ.
func GracePeriodStartedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldGracePeriodStartedAt, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLockedAt, v))
}

// LockReason applies equality check predicate on the "lock_reason" field. It's identical to LockReasonEQ.
func LockReason(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLockReason, v))
}

// LastEvaluationSummary applies equality check predicate on the "last_evaluation_summary" field. It's identical to LastEvaluationSummaryEQ.
func LastEvaluationSummary(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastEvaluationSummary, v))
}

// Exempted applies equality check predicate on the "exempted" field. It's identical to ExemptedEQ.
func Exempted(v bool) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExempted, v))
}

// ExemptedAt applies equality check predicate on the "exempted_at" field. It's identical to ExemptedAtEQ.
func ExemptedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptedAt, v))
}

// ExemptedBy applies equality check predicate on the "exempted_by" field. It's identical to ExemptedByEQ.
func ExemptedBy(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptedBy, v))
}

// ExemptionReason applies equality check predicate on the "exemption_reason" field. It's identical to ExemptionReasonEQ.
func ExemptionReason(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptionReason, v))
}

// UnlockedAt applies equality check predicate on the "unlocked_at" field. It's identical to UnlockedAtEQ.
func UnlockedAt(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockedAt, v))
}

// UnlockedBy applies equality check predicate on the "unlocked_by" field. It's identical to UnlockedByEQ.
func UnlockedBy(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockedBy, v))
}

// UnlockReason applies equality check predicate on the "unlock_reason" field. It's identical to UnlockReasonEQ.
func UnlockReason(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldUserID, vs...))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldScore, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContainsFold(FieldStatus, v))
}

// ConsecutiveBadDaysEQ applies the EQ predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysEQ(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldConsecutiveBadDays, v))
}

// ConsecutiveBadDaysNEQ applies the NEQ predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysNEQ(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldConsecutiveBadDays, v))
}

// ConsecutiveBadDaysIn applies the In predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysIn(vs ...int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldConsecutiveBadDays, vs...))
}

// ConsecutiveBadDaysNotIn applies the NotIn predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysNotIn(vs ...int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldConsecutiveBadDays, vs...))
}

// ConsecutiveBadDaysGT applies the GT predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysGT(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldConsecutiveBadDays, v))
}

// ConsecutiveBadDaysGTE applies the GTE predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysGTE(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldConsecutiveBadDays, v))
}

// ConsecutiveBadDaysLT applies the LT predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysLT(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldConsecutiveBadDays, v))
}

// ConsecutiveBadDaysLTE applies the LTE predicate on the "consecutive_bad_days" field.
func ConsecutiveBadDaysLTE(v int) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldConsecutiveBadDays, v))
}

// LastEvaluatedAtEQ applies the EQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtNEQ applies the NEQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIn applies the In predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtNotIn applies the NotIn predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtGT applies the GT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtGTE applies the GTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLT applies the LT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLTE applies the LTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIsNil applies the IsNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldLastEvaluatedAt))
}

// LastEvaluatedAtNotNil applies the NotNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldLastEvaluatedAt))
}

// LastWarnedAtEQ applies the EQ predicate on the "last_warned_at" field.
func LastWarnedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastWarnedAt, v))
}

// LastWarnedAtNEQ applies the NEQ predicate on the "last_warned_at" field.
func LastWarnedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldLastWarnedAt, v))
}

// LastWarnedAtIn applies the In predicate on the "last_warned_at" field.
func LastWarnedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldLastWarnedAt, vs...))
}

// LastWarnedAtNotIn applies the NotIn predicate on the "last_warned_at" field.
func LastWarnedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldLastWarnedAt, vs...))
}

// LastWarnedAtGT applies the GT predicate on the "last_warned_at" field.
func LastWarnedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldLastWarnedAt, v))
}

// LastWarnedAtGTE applies the GTE predicate on the "last_warned_at" field.
func LastWarnedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldLastWarnedAt, v))
}

// LastWarnedAtLT applies the LT predicate on the "last_warned_at" field.
func LastWarnedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldLastWarnedAt, v))
}

// LastWarnedAtLTE applies the LTE predicate on the "last_warned_at" field.
func LastWarnedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldLastWarnedAt, v))
}

// LastWarnedAtIsNil applies the IsNil predicate on the "last_warned_at" field.
func LastWarnedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldLastWarnedAt))
}

// LastWarnedAtNotNil applies the NotNil predicate on the "last_warned_at" field.
func LastWarnedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldLastWarnedAt))
}

// GracePeriodStartedAtEQ applies the EQ predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtNEQ applies the NEQ predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtIn applies the In predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldGracePeriodStartedAt, vs...))
}

// GracePeriodStartedAtNotIn applies the NotIn predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldGracePeriodStartedAt, vs...))
}

// GracePeriodStartedAtGT applies the GT predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtGTE applies the GTE predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtLT applies the LT predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtLTE applies the LTE predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldGracePeriodStartedAt, v))
}

// GracePeriodStartedAtIsNil applies the IsNil predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldGracePeriodStartedAt))
}

// GracePeriodStartedAtNotNil applies the NotNil predicate on the "grace_period_started_at" field.
func GracePeriodStartedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldGracePeriodStartedAt))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldLockedAt))
}

// LockReasonEQ applies the EQ predicate on the "lock_reason" field.
func LockReasonEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLockReason, v))
}

// LockReasonNEQ applies the NEQ predicate on the "lock_reason" field.
func LockReasonNEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldLockReason, v))
}

// LockReasonIn applies the In predicate on the "lock_reason" field.
func LockReasonIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldLockReason, vs...))
}

// LockReasonNotIn applies the NotIn predicate on the "lock_reason" field.
func LockReasonNotIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldLockReason, vs...))
}

// LockReasonGT applies the GT predicate on the "lock_reason" field.
func LockReasonGT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldLockReason, v))
}

// LockReasonGTE applies the GTE predicate on the "lock_reason" field.
func LockReasonGTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldLockReason, v))
}

// LockReasonLT applies the LT predicate on the "lock_reason" field.
func LockReasonLT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldLockReason, v))
}

// LockReasonLTE applies the LTE predicate on the "lock_reason" field.
func LockReasonLTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldLockReason, v))
}

// LockReasonContains applies the Contains predicate on the "lock_reason" field.
func LockReasonContains(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContains(FieldLockReason, v))
}

// LockReasonHasPrefix applies the HasPrefix predicate on the "lock_reason" field.
func LockReasonHasPrefix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasPrefix(FieldLockReason, v))
}

// LockReasonHasSuffix applies the HasSuffix predicate on the "lock_reason" field.
func LockReasonHasSuffix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasSuffix(FieldLockReason, v))
}

// LockReasonEqualFold applies the EqualFold predicate on the "lock_reason" field.
func LockReasonEqualFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEqualFold(FieldLockReason, v))
}

// LockReasonContainsFold applies the ContainsFold predicate on the "lock_reason" field.
func LockReasonContainsFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContainsFold(FieldLockReason, v))
}

// LastEvaluationSummaryEQ applies the EQ predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryNEQ applies the NEQ predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryNEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryIn applies the In predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldLastEvaluationSummary, vs...))
}

// LastEvaluationSummaryNotIn applies the NotIn predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryNotIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldLastEvaluationSummary, vs...))
}

// LastEvaluationSummaryGT applies the GT predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryGT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryGTE applies the GTE predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryGTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryLT applies the LT predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryLT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryLTE applies the LTE predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryLTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryContains applies the Contains predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryContains(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContains(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryHasPrefix applies the HasPrefix predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryHasPrefix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasPrefix(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryHasSuffix applies the HasSuffix predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryHasSuffix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasSuffix(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryEqualFold applies the EqualFold predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryEqualFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEqualFold(FieldLastEvaluationSummary, v))
}

// LastEvaluationSummaryContainsFold applies the ContainsFold predicate on the "last_evaluation_summary" field.
func LastEvaluationSummaryContainsFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContainsFold(FieldLastEvaluationSummary, v))
}

// ExemptedEQ applies the EQ predicate on the "exempted" field.
func ExemptedEQ(v bool) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExempted, v))
}

// ExemptedNEQ applies the NEQ predicate on the "exempted" field.
func ExemptedNEQ(v bool) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldExempted, v))
}

// ExemptedAtEQ applies the EQ predicate on the "exempted_at" field.
func ExemptedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptedAt, v))
}

// ExemptedAtNEQ applies the NEQ predicate on the "exempted_at" field.
func ExemptedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldExemptedAt, v))
}

// ExemptedAtIn applies the In predicate on the "exempted_at" field.
func ExemptedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldExemptedAt, vs...))
}

// ExemptedAtNotIn applies the NotIn predicate on the "exempted_at" field.
func ExemptedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldExemptedAt, vs...))
}

// ExemptedAtGT applies the GT predicate on the "exempted_at" field.
func ExemptedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldExemptedAt, v))
}

// ExemptedAtGTE applies the GTE predicate on the "exempted_at" field.
func ExemptedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldExemptedAt, v))
}

// ExemptedAtLT applies the LT predicate on the "exempted_at" field.
func ExemptedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldExemptedAt, v))
}

// ExemptedAtLTE applies the LTE predicate on the "exempted_at" field.
func ExemptedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldExemptedAt, v))
}

// ExemptedAtIsNil applies the IsNil predicate on the "exempted_at" field.
func ExemptedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldExemptedAt))
}

// ExemptedAtNotNil applies the NotNil predicate on the "exempted_at" field.
func ExemptedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldExemptedAt))
}

// ExemptedByEQ applies the EQ predicate on the "exempted_by" field.
func ExemptedByEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptedBy, v))
}

// ExemptedByNEQ applies the NEQ predicate on the "exempted_by" field.
func ExemptedByNEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldExemptedBy, v))
}

// ExemptedByIn applies the In predicate on the "exempted_by" field.
func ExemptedByIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldExemptedBy, vs...))
}

// ExemptedByNotIn applies the NotIn predicate on the "exempted_by" field.
func ExemptedByNotIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldExemptedBy, vs...))
}

// ExemptedByGT applies the GT predicate on the "exempted_by" field.
func ExemptedByGT(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldExemptedBy, v))
}

// ExemptedByGTE applies the GTE predicate on the "exempted_by" field.
func ExemptedByGTE(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldExemptedBy, v))
}

// ExemptedByLT applies the LT predicate on the "exempted_by" field.
func ExemptedByLT(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldExemptedBy, v))
}

// ExemptedByLTE applies the LTE predicate on the "exempted_by" field.
func ExemptedByLTE(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldExemptedBy, v))
}

// ExemptedByIsNil applies the IsNil predicate on the "exempted_by" field.
func ExemptedByIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldExemptedBy))
}

// ExemptedByNotNil applies the NotNil predicate on the "exempted_by" field.
func ExemptedByNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldExemptedBy))
}

// ExemptionReasonEQ applies the EQ predicate on the "exemption_reason" field.
func ExemptionReasonEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldExemptionReason, v))
}

// ExemptionReasonNEQ applies the NEQ predicate on the "exemption_reason" field.
func ExemptionReasonNEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldExemptionReason, v))
}

// ExemptionReasonIn applies the In predicate on the "exemption_reason" field.
func ExemptionReasonIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldExemptionReason, vs...))
}

// ExemptionReasonNotIn applies the NotIn predicate on the "exemption_reason" field.
func ExemptionReasonNotIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldExemptionReason, vs...))
}

// ExemptionReasonGT applies the GT predicate on the "exemption_reason" field.
func ExemptionReasonGT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldExemptionReason, v))
}

// ExemptionReasonGTE applies the GTE predicate on the "exemption_reason" field.
func ExemptionReasonGTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldExemptionReason, v))
}

// ExemptionReasonLT applies the LT predicate on the "exemption_reason" field.
func ExemptionReasonLT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldExemptionReason, v))
}

// ExemptionReasonLTE applies the LTE predicate on the "exemption_reason" field.
func ExemptionReasonLTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldExemptionReason, v))
}

// ExemptionReasonContains applies the Contains predicate on the "exemption_reason" field.
func ExemptionReasonContains(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContains(FieldExemptionReason, v))
}

// ExemptionReasonHasPrefix applies the HasPrefix predicate on the "exemption_reason" field.
func ExemptionReasonHasPrefix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasPrefix(FieldExemptionReason, v))
}

// ExemptionReasonHasSuffix applies the HasSuffix predicate on the "exemption_reason" field.
func ExemptionReasonHasSuffix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasSuffix(FieldExemptionReason, v))
}

// ExemptionReasonEqualFold applies the EqualFold predicate on the "exemption_reason" field.
func ExemptionReasonEqualFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEqualFold(FieldExemptionReason, v))
}

// ExemptionReasonContainsFold applies the ContainsFold predicate on the "exemption_reason" field.
func ExemptionReasonContainsFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContainsFold(FieldExemptionReason, v))
}

// UnlockedAtEQ applies the EQ predicate on the "unlocked_at" field.
func UnlockedAtEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockedAt, v))
}

// UnlockedAtNEQ applies the NEQ predicate on the "unlocked_at" field.
func UnlockedAtNEQ(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldUnlockedAt, v))
}

// UnlockedAtIn applies the In predicate on the "unlocked_at" field.
func UnlockedAtIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldUnlockedAt, vs...))
}

// UnlockedAtNotIn applies the NotIn predicate on the "unlocked_at" field.
func UnlockedAtNotIn(vs ...time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldUnlockedAt, vs...))
}

// UnlockedAtGT applies the GT predicate on the "unlocked_at" field.
func UnlockedAtGT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldUnlockedAt, v))
}

// UnlockedAtGTE applies the GTE predicate on the "unlocked_at" field.
func UnlockedAtGTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldUnlockedAt, v))
}

// UnlockedAtLT applies the LT predicate on the "unlocked_at" field.
func UnlockedAtLT(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldUnlockedAt, v))
}

// UnlockedAtLTE applies the LTE predicate on the "unlocked_at" field.
func UnlockedAtLTE(v time.Time) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldUnlockedAt, v))
}

// UnlockedAtIsNil applies the IsNil predicate on the "unlocked_at" field.
func UnlockedAtIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldUnlockedAt))
}

// UnlockedAtNotNil applies the NotNil predicate on the "unlocked_at" field.
func UnlockedAtNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldUnlockedAt))
}

// UnlockedByEQ applies the EQ predicate on the "unlocked_by" field.
func UnlockedByEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockedBy, v))
}

// UnlockedByNEQ applies the NEQ predicate on the "unlocked_by" field.
func UnlockedByNEQ(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldUnlockedBy, v))
}

// UnlockedByIn applies the In predicate on the "unlocked_by" field.
func UnlockedByIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldUnlockedBy, vs...))
}

// UnlockedByNotIn applies the NotIn predicate on the "unlocked_by" field.
func UnlockedByNotIn(vs ...int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldUnlockedBy, vs...))
}

// UnlockedByGT applies the GT predicate on the "unlocked_by" field.
func UnlockedByGT(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldUnlockedBy, v))
}

// UnlockedByGTE applies the GTE predicate on the "unlocked_by" field.
func UnlockedByGTE(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldUnlockedBy, v))
}

// UnlockedByLT applies the LT predicate on the "unlocked_by" field.
func UnlockedByLT(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldUnlockedBy, v))
}

// UnlockedByLTE applies the LTE predicate on the "unlocked_by" field.
func UnlockedByLTE(v int64) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldUnlockedBy, v))
}

// UnlockedByIsNil applies the IsNil predicate on the "unlocked_by" field.
func UnlockedByIsNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIsNull(FieldUnlockedBy))
}

// UnlockedByNotNil applies the NotNil predicate on the "unlocked_by" field.
func UnlockedByNotNil() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotNull(FieldUnlockedBy))
}

// UnlockReasonEQ applies the EQ predicate on the "unlock_reason" field.
func UnlockReasonEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEQ(FieldUnlockReason, v))
}

// UnlockReasonNEQ applies the NEQ predicate on the "unlock_reason" field.
func UnlockReasonNEQ(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNEQ(FieldUnlockReason, v))
}

// UnlockReasonIn applies the In predicate on the "unlock_reason" field.
func UnlockReasonIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldIn(FieldUnlockReason, vs...))
}

// UnlockReasonNotIn applies the NotIn predicate on the "unlock_reason" field.
func UnlockReasonNotIn(vs ...string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldNotIn(FieldUnlockReason, vs...))
}

// UnlockReasonGT applies the GT predicate on the "unlock_reason" field.
func UnlockReasonGT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGT(FieldUnlockReason, v))
}

// UnlockReasonGTE applies the GTE predicate on the "unlock_reason" field.
func UnlockReasonGTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldGTE(FieldUnlockReason, v))
}

// UnlockReasonLT applies the LT predicate on the "unlock_reason" field.
func UnlockReasonLT(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLT(FieldUnlockReason, v))
}

// UnlockReasonLTE applies the LTE predicate on the "unlock_reason" field.
func UnlockReasonLTE(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldLTE(FieldUnlockReason, v))
}

// UnlockReasonContains applies the Contains predicate on the "unlock_reason" field.
func UnlockReasonContains(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContains(FieldUnlockReason, v))
}

// UnlockReasonHasPrefix applies the HasPrefix predicate on the "unlock_reason" field.
func UnlockReasonHasPrefix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasPrefix(FieldUnlockReason, v))
}

// UnlockReasonHasSuffix applies the HasSuffix predicate on the "unlock_reason" field.
func UnlockReasonHasSuffix(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldHasSuffix(FieldUnlockReason, v))
}

// UnlockReasonEqualFold applies the EqualFold predicate on the "unlock_reason" field.
func UnlockReasonEqualFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldEqualFold(FieldUnlockReason, v))
}

// UnlockReasonContainsFold applies the ContainsFold predicate on the "unlock_reason" field.
func UnlockReasonContainsFold(v string) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.FieldContainsFold(FieldUnlockReason, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserRiskProfile {
	return predicate.UserRiskProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRiskProfile) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRiskProfile) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRiskProfile) predicate.UserRiskProfile {
	return predicate.UserRiskProfile(sql.NotPredicates(p))
}
