// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxyprobelog"
)

// ProxyProbeLogCreate is the builder for creating a ProxyProbeLog entity.
type ProxyProbeLogCreate struct {
	config
	mutation *ProxyProbeLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProxyID sets the "proxy_id" field.
func (_c *ProxyProbeLogCreate) SetProxyID(v int64) *ProxyProbeLogCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *ProxyProbeLogCreate) SetSource(v string) *ProxyProbeLogCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableSource(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *ProxyProbeLogCreate) SetTarget(v string) *ProxyProbeLogCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableTarget(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *ProxyProbeLogCreate) SetSuccess(v bool) *ProxyProbeLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableSuccess(v *bool) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *ProxyProbeLogCreate) SetLatencyMs(v int64) *ProxyProbeLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableLatencyMs(v *int64) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ProxyProbeLogCreate) SetErrorMessage(v string) *ProxyProbeLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableErrorMessage(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *ProxyProbeLogCreate) SetIPAddress(v string) *ProxyProbeLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableIPAddress(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetCountryCode sets the "country_code" field.
func (_c *ProxyProbeLogCreate) SetCountryCode(v string) *ProxyProbeLogCreate {
	_c.mutation.SetCountryCode(v)
	return _c
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableCountryCode(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetCountryCode(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *ProxyProbeLogCreate) SetCountry(v string) *ProxyProbeLogCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableCountry(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *ProxyProbeLogCreate) SetRegion(v string) *ProxyProbeLogCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableRegion(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *ProxyProbeLogCreate) SetCity(v string) *ProxyProbeLogCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableCity(v *string) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetCheckedAt sets the "checked_at" field.
func (_c *ProxyProbeLogCreate) SetCheckedAt(v time.Time) *ProxyProbeLogCreate {
	_c.mutation.SetCheckedAt(v)
	return _c
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableCheckedAt(v *time.Time) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetCheckedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyProbeLogCreate) SetCreatedAt(v time.Time) *ProxyProbeLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyProbeLogCreate) SetNillableCreatedAt(v *time.Time) *ProxyProbeLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ProxyProbeLogMutation object of the builder.
func (_c *ProxyProbeLogCreate) Mutation() *ProxyProbeLogMutation {
	return _c.mutation
}

// Save creates the ProxyProbeLog in the database.
func (_c *ProxyProbeLogCreate) Save(ctx context.Context) (*ProxyProbeLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyProbeLogCreate) SaveX(ctx context.Context) *ProxyProbeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyProbeLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyProbeLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyProbeLogCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := proxyprobelog.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := proxyprobelog.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := proxyprobelog.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		v := proxyprobelog.DefaultCheckedAt()
		_c.mutation.SetCheckedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyprobelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyProbeLogCreate) check() error {
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "ProxyProbeLog.proxy_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ProxyProbeLog.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := proxyprobelog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "ProxyProbeLog.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := proxyprobelog.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "ProxyProbeLog.success"`)}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := proxyprobelog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.error_message": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := proxyprobelog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CountryCode(); ok {
		if err := proxyprobelog.CountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "country_code", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.country_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := proxyprobelog.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := proxyprobelog.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.region": %w`, err)}
		}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := proxyprobelog.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ProxyProbeLog.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		return &ValidationError{Name: "checked_at", err: errors.New(`ent: missing required field "ProxyProbeLog.checked_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyProbeLog.created_at"`)}
	}
	return nil
}

func (_c *ProxyProbeLogCreate) sqlSave(ctx context.Context) (*ProxyProbeLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyProbeLogCreate) createSpec() (*ProxyProbeLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyProbeLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyprobelog.Table, sqlgraph.NewFieldSpec(proxyprobelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProxyID(); ok {
		_spec.SetField(proxyprobelog.FieldProxyID, field.TypeInt64, value)
		_node.ProxyID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(proxyprobelog.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(proxyprobelog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(proxyprobelog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(proxyprobelog.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(proxyprobelog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(proxyprobelog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.CountryCode(); ok {
		_spec.SetField(proxyprobelog.FieldCountryCode, field.TypeString, value)
		_node.CountryCode = &value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(proxyprobelog.FieldCountry, field.TypeString, value)
		_node.Country = &value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(proxyprobelog.FieldRegion, field.TypeString, value)
		_node.Region = &value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(proxyprobelog.FieldCity, field.TypeString, value)
		_node.City = &value
	}
	if value, ok := _c.mutation.CheckedAt(); ok {
		_spec.SetField(proxyprobelog.FieldCheckedAt, field.TypeTime, value)
		_node.CheckedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyprobelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyProbeLog.Create().
//		SetProxyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyProbeLogUpsert) {
//			SetProxyID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyProbeLogCreate) OnConflict(opts ...sql.ConflictOption) *ProxyProbeLogUpsertOne {
	_c.conflict = opts
	return &ProxyProbeLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyProbeLogCreate) OnConflictColumns(columns ...string) *ProxyProbeLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyProbeLogUpsertOne{
		create: _c,
	}
}

type (
	// ProxyProbeLogUpsertOne is the builder for "upsert"-ing
	//  one ProxyProbeLog node.
	ProxyProbeLogUpsertOne struct {
		create *ProxyProbeLogCreate
	}

	// ProxyProbeLogUpsert is the "OnConflict" setter.
	ProxyProbeLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetProxyID sets the "proxy_id" field.
func (u *ProxyProbeLogUpsert) SetProxyID(v int64) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateProxyID() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldProxyID)
	return u
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyProbeLogUpsert) AddProxyID(v int64) *ProxyProbeLogUpsert {
	u.Add(proxyprobelog.FieldProxyID, v)
	return u
}

// SetSource sets the "source" field.
func (u *ProxyProbeLogUpsert) SetSource(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateSource() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldSource)
	return u
}

// SetTarget sets the "target" field.
func (u *ProxyProbeLogUpsert) SetTarget(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateTarget() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldTarget)
	return u
}

// SetSuccess sets the "success" field.
func (u *ProxyProbeLogUpsert) SetSuccess(v bool) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateSuccess() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldSuccess)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *ProxyProbeLogUpsert) SetLatencyMs(v int64) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateLatencyMs() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *ProxyProbeLogUpsert) AddLatencyMs(v int64) *ProxyProbeLogUpsert {
	u.Add(proxyprobelog.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *ProxyProbeLogUpsert) ClearLatencyMs() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldLatencyMs)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ProxyProbeLogUpsert) SetErrorMessage(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateErrorMessage() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProxyProbeLogUpsert) ClearErrorMessage() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldErrorMessage)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyProbeLogUpsert) SetIPAddress(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateIPAddress() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *ProxyProbeLogUpsert) ClearIPAddress() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldIPAddress)
	return u
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyProbeLogUpsert) SetCountryCode(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldCountryCode, v)
	return u
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateCountryCode() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldCountryCode)
	return u
}

// ClearCountryCode clears the value of the "country_code" field.
func (u *ProxyProbeLogUpsert) ClearCountryCode() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldCountryCode)
	return u
}

// SetCountry sets the "country" field.
func (u *ProxyProbeLogUpsert) SetCountry(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateCountry() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldCountry)
	return u
}

// ClearCountry clears the value of the "country" field.
func (u *ProxyProbeLogUpsert) ClearCountry() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldCountry)
	return u
}

// SetRegion sets the "region" field.
func (u *ProxyProbeLogUpsert) SetRegion(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldRegion, v)
	return u
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateRegion() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldRegion)
	return u
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyProbeLogUpsert) ClearRegion() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldRegion)
	return u
}

// SetCity sets the "city" field.
func (u *ProxyProbeLogUpsert) SetCity(v string) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldCity, v)
	return u
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateCity() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldCity)
	return u
}

// ClearCity clears the value of the "city" field.
func (u *ProxyProbeLogUpsert) ClearCity() *ProxyProbeLogUpsert {
	u.SetNull(proxyprobelog.FieldCity)
	return u
}

// SetCheckedAt sets the "checked_at" field.
func (u *ProxyProbeLogUpsert) SetCheckedAt(v time.Time) *ProxyProbeLogUpsert {
	u.Set(proxyprobelog.FieldCheckedAt, v)
	return u
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *ProxyProbeLogUpsert) UpdateCheckedAt() *ProxyProbeLogUpsert {
	u.SetExcluded(proxyprobelog.FieldCheckedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyProbeLogUpsertOne) UpdateNewValues() *ProxyProbeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxyprobelog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyProbeLogUpsertOne) Ignore() *ProxyProbeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyProbeLogUpsertOne) DoNothing() *ProxyProbeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyProbeLogCreate.OnConflict
// documentation for more info.
func (u *ProxyProbeLogUpsertOne) Update(set func(*ProxyProbeLogUpsert)) *ProxyProbeLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyProbeLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *ProxyProbeLogUpsertOne) SetProxyID(v int64) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyProbeLogUpsertOne) AddProxyID(v int64) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateProxyID() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateProxyID()
	})
}

// SetSource sets the "source" field.
func (u *ProxyProbeLogUpsertOne) SetSource(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateSource() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateSource()
	})
}

// SetTarget sets the "target" field.
func (u *ProxyProbeLogUpsertOne) SetTarget(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateTarget() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateTarget()
	})
}

// SetSuccess sets the "success" field.
func (u *ProxyProbeLogUpsertOne) SetSuccess(v bool) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateSuccess() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateSuccess()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *ProxyProbeLogUpsertOne) SetLatencyMs(v int64) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *ProxyProbeLogUpsertOne) AddLatencyMs(v int64) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateLatencyMs() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *ProxyProbeLogUpsertOne) ClearLatencyMs() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearLatencyMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProxyProbeLogUpsertOne) SetErrorMessage(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateErrorMessage() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProxyProbeLogUpsertOne) ClearErrorMessage() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyProbeLogUpsertOne) SetIPAddress(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateIPAddress() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *ProxyProbeLogUpsertOne) ClearIPAddress() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyProbeLogUpsertOne) SetCountryCode(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCountryCode(v)
	})
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateCountryCode() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCountryCode()
	})
}

// ClearCountryCode clears the value of the "country_code" field.
func (u *ProxyProbeLogUpsertOne) ClearCountryCode() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCountryCode()
	})
}

// SetCountry sets the "country" field.
func (u *ProxyProbeLogUpsertOne) SetCountry(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateCountry() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *ProxyProbeLogUpsertOne) ClearCountry() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCountry()
	})
}

// SetRegion sets the "region" field.
func (u *ProxyProbeLogUpsertOne) SetRegion(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateRegion() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateRegion()
	})
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyProbeLogUpsertOne) ClearRegion() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearRegion()
	})
}

// SetCity sets the "city" field.
func (u *ProxyProbeLogUpsertOne) SetCity(v string) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateCity() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCity()
	})
}

// ClearCity clears the value of the "city" field.
func (u *ProxyProbeLogUpsertOne) ClearCity() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCity()
	})
}

// SetCheckedAt sets the "checked_at" field.
func (u *ProxyProbeLogUpsertOne) SetCheckedAt(v time.Time) *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertOne) UpdateCheckedAt() *ProxyProbeLogUpsertOne {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCheckedAt()
	})
}

// Exec executes the query.
func (u *ProxyProbeLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyProbeLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyProbeLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyProbeLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyProbeLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyProbeLogCreateBulk is the builder for creating many ProxyProbeLog entities in bulk.
type ProxyProbeLogCreateBulk struct {
	config
	err      error
	builders []*ProxyProbeLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyProbeLog entities in the database.
func (_c *ProxyProbeLogCreateBulk) Save(ctx context.Context) ([]*ProxyProbeLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyProbeLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyProbeLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyProbeLogCreateBulk) SaveX(ctx context.Context) []*ProxyProbeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyProbeLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyProbeLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyProbeLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyProbeLogUpsert) {
//			SetProxyID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyProbeLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyProbeLogUpsertBulk {
	_c.conflict = opts
	return &ProxyProbeLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyProbeLogCreateBulk) OnConflictColumns(columns ...string) *ProxyProbeLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyProbeLogUpsertBulk{
		create: _c,
	}
}

// ProxyProbeLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyProbeLog nodes.
type ProxyProbeLogUpsertBulk struct {
	create *ProxyProbeLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyProbeLogUpsertBulk) UpdateNewValues() *ProxyProbeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxyprobelog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyProbeLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyProbeLogUpsertBulk) Ignore() *ProxyProbeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyProbeLogUpsertBulk) DoNothing() *ProxyProbeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyProbeLogCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyProbeLogUpsertBulk) Update(set func(*ProxyProbeLogUpsert)) *ProxyProbeLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyProbeLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *ProxyProbeLogUpsertBulk) SetProxyID(v int64) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyProbeLogUpsertBulk) AddProxyID(v int64) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateProxyID() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateProxyID()
	})
}

// SetSource sets the "source" field.
func (u *ProxyProbeLogUpsertBulk) SetSource(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateSource() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateSource()
	})
}

// SetTarget sets the "target" field.
func (u *ProxyProbeLogUpsertBulk) SetTarget(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateTarget() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateTarget()
	})
}

// SetSuccess sets the "success" field.
func (u *ProxyProbeLogUpsertBulk) SetSuccess(v bool) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateSuccess() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateSuccess()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *ProxyProbeLogUpsertBulk) SetLatencyMs(v int64) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *ProxyProbeLogUpsertBulk) AddLatencyMs(v int64) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateLatencyMs() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *ProxyProbeLogUpsertBulk) ClearLatencyMs() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearLatencyMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProxyProbeLogUpsertBulk) SetErrorMessage(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateErrorMessage() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProxyProbeLogUpsertBulk) ClearErrorMessage() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *ProxyProbeLogUpsertBulk) SetIPAddress(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateIPAddress() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *ProxyProbeLogUpsertBulk) ClearIPAddress() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetCountryCode sets the "country_code" field.
func (u *ProxyProbeLogUpsertBulk) SetCountryCode(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCountryCode(v)
	})
}

// UpdateCountryCode sets the "country_code" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateCountryCode() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCountryCode()
	})
}

// ClearCountryCode clears the value of the "country_code" field.
func (u *ProxyProbeLogUpsertBulk) ClearCountryCode() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCountryCode()
	})
}

// SetCountry sets the "country" field.
func (u *ProxyProbeLogUpsertBulk) SetCountry(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateCountry() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *ProxyProbeLogUpsertBulk) ClearCountry() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCountry()
	})
}

// SetRegion sets the "region" field.
func (u *ProxyProbeLogUpsertBulk) SetRegion(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateRegion() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateRegion()
	})
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyProbeLogUpsertBulk) ClearRegion() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearRegion()
	})
}

// SetCity sets the "city" field.
func (u *ProxyProbeLogUpsertBulk) SetCity(v string) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateCity() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCity()
	})
}

// ClearCity clears the value of the "city" field.
func (u *ProxyProbeLogUpsertBulk) ClearCity() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.ClearCity()
	})
}

// SetCheckedAt sets the "checked_at" field.
func (u *ProxyProbeLogUpsertBulk) SetCheckedAt(v time.Time) *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.SetCheckedAt(v)
	})
}

// UpdateCheckedAt sets the "checked_at" field to the value that was provided on create.
func (u *ProxyProbeLogUpsertBulk) UpdateCheckedAt() *ProxyProbeLogUpsertBulk {
	return u.Update(func(s *ProxyProbeLogUpsert) {
		s.UpdateCheckedAt()
	})
}

// Exec executes the query.
func (u *ProxyProbeLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyProbeLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyProbeLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyProbeLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
