// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskprofile"
)

// UserRiskProfile is the model entity for the UserRiskProfile schema.
type UserRiskProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ConsecutiveBadDays holds the value of the "consecutive_bad_days" field.
	ConsecutiveBadDays int `json:"consecutive_bad_days,omitempty"`
	// LastEvaluatedAt holds the value of the "last_evaluated_at" field.
	LastEvaluatedAt *time.Time `json:"last_evaluated_at,omitempty"`
	// LastWarnedAt holds the value of the "last_warned_at" field.
	LastWarnedAt *time.Time `json:"last_warned_at,omitempty"`
	// GracePeriodStartedAt holds the value of the "grace_period_started_at" field.
	GracePeriodStartedAt *time.Time `json:"grace_period_started_at,omitempty"`
	// LockedAt holds the value of the "locked_at" field.
	LockedAt *time.Time `json:"locked_at,omitempty"`
	// LockReason holds the value of the "lock_reason" field.
	LockReason string `json:"lock_reason,omitempty"`
	// LastEvaluationSummary holds the value of the "last_evaluation_summary" field.
	LastEvaluationSummary string `json:"last_evaluation_summary,omitempty"`
	// Exempted holds the value of the "exempted" field.
	Exempted bool `json:"exempted,omitempty"`
	// ExemptedAt holds the value of the "exempted_at" field.
	ExemptedAt *time.Time `json:"exempted_at,omitempty"`
	// ExemptedBy holds the value of the "exempted_by" field.
	ExemptedBy *int64 `json:"exempted_by,omitempty"`
	// ExemptionReason holds the value of the "exemption_reason" field.
	ExemptionReason string `json:"exemption_reason,omitempty"`
	// UnlockedAt holds the value of the "unlocked_at" field.
	UnlockedAt *time.Time `json:"unlocked_at,omitempty"`
	// UnlockedBy holds the value of the "unlocked_by" field.
	UnlockedBy *int64 `json:"unlocked_by,omitempty"`
	// UnlockReason holds the value of the "unlock_reason" field.
	UnlockReason string `json:"unlock_reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserRiskProfileQuery when eager-loading is set.
	Edges        UserRiskProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserRiskProfileEdges holds the relations/edges for other nodes in the graph.
type UserRiskProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserRiskProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserRiskProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userriskprofile.FieldExempted:
			values[i] = new(sql.NullBool)
		case userriskprofile.FieldScore:
			values[i] = new(sql.NullFloat64)
		case userriskprofile.FieldID, userriskprofile.FieldUserID, userriskprofile.FieldConsecutiveBadDays, userriskprofile.FieldExemptedBy, userriskprofile.FieldUnlockedBy:
			values[i] = new(sql.NullInt64)
		case userriskprofile.FieldStatus, userriskprofile.FieldLockReason, userriskprofile.FieldLastEvaluationSummary, userriskprofile.FieldExemptionReason, userriskprofile.FieldUnlockReason:
			values[i] = new(sql.NullString)
		case userriskprofile.FieldCreatedAt, userriskprofile.FieldUpdatedAt, userriskprofile.FieldLastEvaluatedAt, userriskprofile.FieldLastWarnedAt, userriskprofile.FieldGracePeriodStartedAt, userriskprofile.FieldLockedAt, userriskprofile.FieldExemptedAt, userriskprofile.FieldUnlockedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserRiskProfile fields.
func (_m *UserRiskProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userriskprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userriskprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userriskprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userriskprofile.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userriskprofile.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case userriskprofile.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userriskprofile.FieldConsecutiveBadDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_bad_days", values[i])
			} else if value.Valid {
				_m.ConsecutiveBadDays = int(value.Int64)
			}
		case userriskprofile.FieldLastEvaluatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_evaluated_at", values[i])
			} else if value.Valid {
				_m.LastEvaluatedAt = new(time.Time)
				*_m.LastEvaluatedAt = value.Time
			}
		case userriskprofile.FieldLastWarnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_warned_at", values[i])
			} else if value.Valid {
				_m.LastWarnedAt = new(time.Time)
				*_m.LastWarnedAt = value.Time
			}
		case userriskprofile.FieldGracePeriodStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field grace_period_started_at", values[i])
			} else if value.Valid {
				_m.GracePeriodStartedAt = new(time.Time)
				*_m.GracePeriodStartedAt = value.Time
			}
		case userriskprofile.FieldLockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_at", values[i])
			} else if value.Valid {
				_m.LockedAt = new(time.Time)
				*_m.LockedAt = value.Time
			}
		case userriskprofile.FieldLockReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lock_reason", values[i])
			} else if value.Valid {
				_m.LockReason = value.String
			}
		case userriskprofile.FieldLastEvaluationSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_evaluation_summary", values[i])
			} else if value.Valid {
				_m.LastEvaluationSummary = value.String
			}
		case userriskprofile.FieldExempted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field exempted", values[i])
			} else if value.Valid {
				_m.Exempted = value.Bool
			}
		case userriskprofile.FieldExemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field exempted_at", values[i])
			} else if value.Valid {
				_m.ExemptedAt = new(time.Time)
				*_m.ExemptedAt = value.Time
			}
		case userriskprofile.FieldExemptedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exempted_by", values[i])
			} else if value.Valid {
				_m.ExemptedBy = new(int64)
				*_m.ExemptedBy = value.Int64
			}
		case userriskprofile.FieldExemptionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exemption_reason", values[i])
			} else if value.Valid {
				_m.ExemptionReason = value.String
			}
		case userriskprofile.FieldUnlockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unlocked_at", values[i])
			} else if value.Valid {
				_m.UnlockedAt = new(time.Time)
				*_m.UnlockedAt = value.Time
			}
		case userriskprofile.FieldUnlockedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unlocked_by", values[i])
			} else if value.Valid {
				_m.UnlockedBy = new(int64)
				*_m.UnlockedBy = value.Int64
			}
		case userriskprofile.FieldUnlockReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unlock_reason", values[i])
			} else if value.Valid {
				_m.UnlockReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserRiskProfile.
// This includes values selected through modifiers, order, etc.
func (_m *UserRiskProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserRiskProfile entity.
func (_m *UserRiskProfile) QueryUser() *UserQuery {
	return NewUserRiskProfileClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserRiskProfile.
// Note that you need to call UserRiskProfile.Unwrap() before calling this method if this UserRiskProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserRiskProfile) Update() *UserRiskProfileUpdateOne {
	return NewUserRiskProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserRiskProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserRiskProfile) Unwrap() *UserRiskProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserRiskProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserRiskProfile) String() string {
	var builder strings.Builder
	builder.WriteString("UserRiskProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("consecutive_bad_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveBadDays))
	builder.WriteString(", ")
	if v := _m.LastEvaluatedAt; v != nil {
		builder.WriteString("last_evaluated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastWarnedAt; v != nil {
		builder.WriteString("last_warned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GracePeriodStartedAt; v != nil {
		builder.WriteString("grace_period_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LockedAt; v != nil {
		builder.WriteString("locked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("lock_reason=")
	builder.WriteString(_m.LockReason)
	builder.WriteString(", ")
	builder.WriteString("last_evaluation_summary=")
	builder.WriteString(_m.LastEvaluationSummary)
	builder.WriteString(", ")
	builder.WriteString("exempted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exempted))
	builder.WriteString(", ")
	if v := _m.ExemptedAt; v != nil {
		builder.WriteString("exempted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExemptedBy; v != nil {
		builder.WriteString("exempted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("exemption_reason=")
	builder.WriteString(_m.ExemptionReason)
	builder.WriteString(", ")
	if v := _m.UnlockedAt; v != nil {
		builder.WriteString("unlocked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UnlockedBy; v != nil {
		builder.WriteString("unlocked_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("unlock_reason=")
	builder.WriteString(_m.UnlockReason)
	builder.WriteByte(')')
	return builder.String()
}

// UserRiskProfiles is a parsable slice of UserRiskProfile.
type UserRiskProfiles []*UserRiskProfile
