// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskevent"
)

// UserRiskEventCreate is the builder for creating a UserRiskEvent entity.
type UserRiskEventCreate struct {
	config
	mutation *UserRiskEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRiskEventCreate) SetCreatedAt(v time.Time) *UserRiskEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableCreatedAt(v *time.Time) *UserRiskEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRiskEventCreate) SetUpdatedAt(v time.Time) *UserRiskEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableUpdatedAt(v *time.Time) *UserRiskEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserRiskEventCreate) SetUserID(v int64) *UserRiskEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *UserRiskEventCreate) SetEventType(v string) *UserRiskEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *UserRiskEventCreate) SetSeverity(v string) *UserRiskEventCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableSeverity(v *string) *UserRiskEventCreate {
	if v != nil {
		_c.SetSeverity(*v)
	}
	return _c
}

// SetScoreDelta sets the "score_delta" field.
func (_c *UserRiskEventCreate) SetScoreDelta(v float64) *UserRiskEventCreate {
	_c.mutation.SetScoreDelta(v)
	return _c
}

// SetNillableScoreDelta sets the "score_delta" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableScoreDelta(v *float64) *UserRiskEventCreate {
	if v != nil {
		_c.SetScoreDelta(*v)
	}
	return _c
}

// SetScoreAfter sets the "score_after" field.
func (_c *UserRiskEventCreate) SetScoreAfter(v float64) *UserRiskEventCreate {
	_c.mutation.SetScoreAfter(v)
	return _c
}

// SetNillableScoreAfter sets the "score_after" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableScoreAfter(v *float64) *UserRiskEventCreate {
	if v != nil {
		_c.SetScoreAfter(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *UserRiskEventCreate) SetSummary(v string) *UserRiskEventCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableSummary(v *string) *UserRiskEventCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UserRiskEventCreate) SetMetadata(v map[string]interface{}) *UserRiskEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetWindowStart sets the "window_start" field.
func (_c *UserRiskEventCreate) SetWindowStart(v time.Time) *UserRiskEventCreate {
	_c.mutation.SetWindowStart(v)
	return _c
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableWindowStart(v *time.Time) *UserRiskEventCreate {
	if v != nil {
		_c.SetWindowStart(*v)
	}
	return _c
}

// SetWindowEnd sets the "window_end" field.
func (_c *UserRiskEventCreate) SetWindowEnd(v time.Time) *UserRiskEventCreate {
	_c.mutation.SetWindowEnd(v)
	return _c
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_c *UserRiskEventCreate) SetNillableWindowEnd(v *time.Time) *UserRiskEventCreate {
	if v != nil {
		_c.SetWindowEnd(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserRiskEventCreate) SetUser(v *User) *UserRiskEventCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserRiskEventMutation object of the builder.
func (_c *UserRiskEventCreate) Mutation() *UserRiskEventMutation {
	return _c.mutation
}

// Save creates the UserRiskEvent in the database.
func (_c *UserRiskEventCreate) Save(ctx context.Context) (*UserRiskEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRiskEventCreate) SaveX(ctx context.Context) *UserRiskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRiskEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRiskEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRiskEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userriskevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userriskevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Severity(); !ok {
		v := userriskevent.DefaultSeverity
		_c.mutation.SetSeverity(v)
	}
	if _, ok := _c.mutation.ScoreDelta(); !ok {
		v := userriskevent.DefaultScoreDelta
		_c.mutation.SetScoreDelta(v)
	}
	if _, ok := _c.mutation.ScoreAfter(); !ok {
		v := userriskevent.DefaultScoreAfter
		_c.mutation.SetScoreAfter(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := userriskevent.DefaultSummary
		_c.mutation.SetSummary(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRiskEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRiskEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRiskEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRiskEvent.user_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "UserRiskEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := userriskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "UserRiskEvent.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := userriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScoreDelta(); !ok {
		return &ValidationError{Name: "score_delta", err: errors.New(`ent: missing required field "UserRiskEvent.score_delta"`)}
	}
	if _, ok := _c.mutation.ScoreAfter(); !ok {
		return &ValidationError{Name: "score_after", err: errors.New(`ent: missing required field "UserRiskEvent.score_after"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "UserRiskEvent.summary"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserRiskEvent.user"`)}
	}
	return nil
}

func (_c *UserRiskEventCreate) sqlSave(ctx context.Context) (*UserRiskEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRiskEventCreate) createSpec() (*UserRiskEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRiskEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userriskevent.Table, sqlgraph.NewFieldSpec(userriskevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userriskevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(userriskevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(userriskevent.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.ScoreDelta(); ok {
		_spec.SetField(userriskevent.FieldScoreDelta, field.TypeFloat64, value)
		_node.ScoreDelta = value
	}
	if value, ok := _c.mutation.ScoreAfter(); ok {
		_spec.SetField(userriskevent.FieldScoreAfter, field.TypeFloat64, value)
		_node.ScoreAfter = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(userriskevent.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(userriskevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.WindowStart(); ok {
		_spec.SetField(userriskevent.FieldWindowStart, field.TypeTime, value)
		_node.WindowStart = &value
	}
	if value, ok := _c.mutation.WindowEnd(); ok {
		_spec.SetField(userriskevent.FieldWindowEnd, field.TypeTime, value)
		_node.WindowEnd = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userriskevent.UserTable,
			Columns: []string{userriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRiskEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRiskEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRiskEventCreate) OnConflict(opts ...sql.ConflictOption) *UserRiskEventUpsertOne {
	_c.conflict = opts
	return &UserRiskEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRiskEventCreate) OnConflictColumns(columns ...string) *UserRiskEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRiskEventUpsertOne{
		create: _c,
	}
}

type (
	// UserRiskEventUpsertOne is the builder for "upsert"-ing
	//  one UserRiskEvent node.
	UserRiskEventUpsertOne struct {
		create *UserRiskEventCreate
	}

	// UserRiskEventUpsert is the "OnConflict" setter.
	UserRiskEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskEventUpsert) SetUpdatedAt(v time.Time) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateUpdatedAt() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRiskEventUpsert) SetUserID(v int64) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateUserID() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldUserID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *UserRiskEventUpsert) SetEventType(v string) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateEventType() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldEventType)
	return u
}

// SetSeverity sets the "severity" field.
func (u *UserRiskEventUpsert) SetSeverity(v string) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateSeverity() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldSeverity)
	return u
}

// SetScoreDelta sets the "score_delta" field.
func (u *UserRiskEventUpsert) SetScoreDelta(v float64) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldScoreDelta, v)
	return u
}

// UpdateScoreDelta sets the "score_delta" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateScoreDelta() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldScoreDelta)
	return u
}

// AddScoreDelta adds v to the "score_delta" field.
func (u *UserRiskEventUpsert) AddScoreDelta(v float64) *UserRiskEventUpsert {
	u.Add(userriskevent.FieldScoreDelta, v)
	return u
}

// SetScoreAfter sets the "score_after" field.
func (u *UserRiskEventUpsert) SetScoreAfter(v float64) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldScoreAfter, v)
	return u
}

// UpdateScoreAfter sets the "score_after" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateScoreAfter() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldScoreAfter)
	return u
}

// AddScoreAfter adds v to the "score_after" field.
func (u *UserRiskEventUpsert) AddScoreAfter(v float64) *UserRiskEventUpsert {
	u.Add(userriskevent.FieldScoreAfter, v)
	return u
}

// SetSummary sets the "summary" field.
func (u *UserRiskEventUpsert) SetSummary(v string) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateSummary() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldSummary)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *UserRiskEventUpsert) SetMetadata(v map[string]interface{}) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateMetadata() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserRiskEventUpsert) ClearMetadata() *UserRiskEventUpsert {
	u.SetNull(userriskevent.FieldMetadata)
	return u
}

// SetWindowStart sets the "window_start" field.
func (u *UserRiskEventUpsert) SetWindowStart(v time.Time) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldWindowStart, v)
	return u
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateWindowStart() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldWindowStart)
	return u
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *UserRiskEventUpsert) ClearWindowStart() *UserRiskEventUpsert {
	u.SetNull(userriskevent.FieldWindowStart)
	return u
}

// SetWindowEnd sets the "window_end" field.
func (u *UserRiskEventUpsert) SetWindowEnd(v time.Time) *UserRiskEventUpsert {
	u.Set(userriskevent.FieldWindowEnd, v)
	return u
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *UserRiskEventUpsert) UpdateWindowEnd() *UserRiskEventUpsert {
	u.SetExcluded(userriskevent.FieldWindowEnd)
	return u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *UserRiskEventUpsert) ClearWindowEnd() *UserRiskEventUpsert {
	u.SetNull(userriskevent.FieldWindowEnd)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRiskEventUpsertOne) UpdateNewValues() *UserRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userriskevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRiskEventUpsertOne) Ignore() *UserRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRiskEventUpsertOne) DoNothing() *UserRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRiskEventCreate.OnConflict
// documentation for more info.
func (u *UserRiskEventUpsertOne) Update(set func(*UserRiskEventUpsert)) *UserRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRiskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskEventUpsertOne) SetUpdatedAt(v time.Time) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateUpdatedAt() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRiskEventUpsertOne) SetUserID(v int64) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateUserID() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateUserID()
	})
}

// SetEventType sets the "event_type" field.
func (u *UserRiskEventUpsertOne) SetEventType(v string) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateEventType() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateEventType()
	})
}

// SetSeverity sets the "severity" field.
func (u *UserRiskEventUpsertOne) SetSeverity(v string) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateSeverity() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetScoreDelta sets the "score_delta" field.
func (u *UserRiskEventUpsertOne) SetScoreDelta(v float64) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetScoreDelta(v)
	})
}

// AddScoreDelta adds v to the "score_delta" field.
func (u *UserRiskEventUpsertOne) AddScoreDelta(v float64) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.AddScoreDelta(v)
	})
}

// UpdateScoreDelta sets the "score_delta" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateScoreDelta() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateScoreDelta()
	})
}

// SetScoreAfter sets the "score_after" field.
func (u *UserRiskEventUpsertOne) SetScoreAfter(v float64) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetScoreAfter(v)
	})
}

// AddScoreAfter adds v to the "score_after" field.
func (u *UserRiskEventUpsertOne) AddScoreAfter(v float64) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.AddScoreAfter(v)
	})
}

// UpdateScoreAfter sets the "score_after" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateScoreAfter() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateScoreAfter()
	})
}

// SetSummary sets the "summary" field.
func (u *UserRiskEventUpsertOne) SetSummary(v string) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateSummary() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateSummary()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UserRiskEventUpsertOne) SetMetadata(v map[string]interface{}) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateMetadata() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserRiskEventUpsertOne) ClearMetadata() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearMetadata()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *UserRiskEventUpsertOne) SetWindowStart(v time.Time) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateWindowStart() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateWindowStart()
	})
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *UserRiskEventUpsertOne) ClearWindowStart() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *UserRiskEventUpsertOne) SetWindowEnd(v time.Time) *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *UserRiskEventUpsertOne) UpdateWindowEnd() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateWindowEnd()
	})
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *UserRiskEventUpsertOne) ClearWindowEnd() *UserRiskEventUpsertOne {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearWindowEnd()
	})
}

// Exec executes the query.
func (u *UserRiskEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRiskEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRiskEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRiskEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRiskEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRiskEventCreateBulk is the builder for creating many UserRiskEvent entities in bulk.
type UserRiskEventCreateBulk struct {
	config
	err      error
	builders []*UserRiskEventCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRiskEvent entities in the database.
func (_c *UserRiskEventCreateBulk) Save(ctx context.Context) ([]*UserRiskEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRiskEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRiskEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRiskEventCreateBulk) SaveX(ctx context.Context) []*UserRiskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRiskEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRiskEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRiskEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRiskEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRiskEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRiskEventUpsertBulk {
	_c.conflict = opts
	return &UserRiskEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRiskEventCreateBulk) OnConflictColumns(columns ...string) *UserRiskEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRiskEventUpsertBulk{
		create: _c,
	}
}

// UserRiskEventUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRiskEvent nodes.
type UserRiskEventUpsertBulk struct {
	create *UserRiskEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRiskEventUpsertBulk) UpdateNewValues() *UserRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userriskevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRiskEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRiskEventUpsertBulk) Ignore() *UserRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRiskEventUpsertBulk) DoNothing() *UserRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRiskEventCreateBulk.OnConflict
// documentation for more info.
func (u *UserRiskEventUpsertBulk) Update(set func(*UserRiskEventUpsert)) *UserRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRiskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskEventUpsertBulk) SetUpdatedAt(v time.Time) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateUpdatedAt() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRiskEventUpsertBulk) SetUserID(v int64) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateUserID() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateUserID()
	})
}

// SetEventType sets the "event_type" field.
func (u *UserRiskEventUpsertBulk) SetEventType(v string) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateEventType() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateEventType()
	})
}

// SetSeverity sets the "severity" field.
func (u *UserRiskEventUpsertBulk) SetSeverity(v string) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateSeverity() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetScoreDelta sets the "score_delta" field.
func (u *UserRiskEventUpsertBulk) SetScoreDelta(v float64) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetScoreDelta(v)
	})
}

// AddScoreDelta adds v to the "score_delta" field.
func (u *UserRiskEventUpsertBulk) AddScoreDelta(v float64) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.AddScoreDelta(v)
	})
}

// UpdateScoreDelta sets the "score_delta" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateScoreDelta() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateScoreDelta()
	})
}

// SetScoreAfter sets the "score_after" field.
func (u *UserRiskEventUpsertBulk) SetScoreAfter(v float64) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetScoreAfter(v)
	})
}

// AddScoreAfter adds v to the "score_after" field.
func (u *UserRiskEventUpsertBulk) AddScoreAfter(v float64) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.AddScoreAfter(v)
	})
}

// UpdateScoreAfter sets the "score_after" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateScoreAfter() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateScoreAfter()
	})
}

// SetSummary sets the "summary" field.
func (u *UserRiskEventUpsertBulk) SetSummary(v string) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateSummary() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateSummary()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UserRiskEventUpsertBulk) SetMetadata(v map[string]interface{}) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateMetadata() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserRiskEventUpsertBulk) ClearMetadata() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearMetadata()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *UserRiskEventUpsertBulk) SetWindowStart(v time.Time) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateWindowStart() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateWindowStart()
	})
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *UserRiskEventUpsertBulk) ClearWindowStart() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *UserRiskEventUpsertBulk) SetWindowEnd(v time.Time) *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *UserRiskEventUpsertBulk) UpdateWindowEnd() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.UpdateWindowEnd()
	})
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *UserRiskEventUpsertBulk) ClearWindowEnd() *UserRiskEventUpsertBulk {
	return u.Update(func(s *UserRiskEventUpsert) {
		s.ClearWindowEnd()
	})
}

// Exec executes the query.
func (u *UserRiskEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRiskEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRiskEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRiskEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
