// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskprofile"
)

// UserRiskProfileCreate is the builder for creating a UserRiskProfile entity.
type UserRiskProfileCreate struct {
	config
	mutation *UserRiskProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRiskProfileCreate) SetCreatedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableCreatedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRiskProfileCreate) SetUpdatedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableUpdatedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserRiskProfileCreate) SetUserID(v int64) *UserRiskProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *UserRiskProfileCreate) SetScore(v float64) *UserRiskProfileCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableScore(v *float64) *UserRiskProfileCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserRiskProfileCreate) SetStatus(v string) *UserRiskProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableStatus(v *string) *UserRiskProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (_c *UserRiskProfileCreate) SetConsecutiveBadDays(v int) *UserRiskProfileCreate {
	_c.mutation.SetConsecutiveBadDays(v)
	return _c
}

// SetNillableConsecutiveBadDays sets the "consecutive_bad_days" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableConsecutiveBadDays(v *int) *UserRiskProfileCreate {
	if v != nil {
		_c.SetConsecutiveBadDays(*v)
	}
	return _c
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_c *UserRiskProfileCreate) SetLastEvaluatedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetLastEvaluatedAt(v)
	return _c
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableLastEvaluatedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetLastEvaluatedAt(*v)
	}
	return _c
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (_c *UserRiskProfileCreate) SetLastWarnedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetLastWarnedAt(v)
	return _c
}

// SetNillableLastWarnedAt sets the "last_warned_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableLastWarnedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetLastWarnedAt(*v)
	}
	return _c
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (_c *UserRiskProfileCreate) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetGracePeriodStartedAt(v)
	return _c
}

// SetNillableGracePeriodStartedAt sets the "grace_period_started_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableGracePeriodStartedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetGracePeriodStartedAt(*v)
	}
	return _c
}

// SetLockedAt sets the "locked_at" field.
func (_c *UserRiskProfileCreate) SetLockedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetLockedAt(v)
	return _c
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableLockedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetLockedAt(*v)
	}
	return _c
}

// SetLockReason sets the "lock_reason" field.
func (_c *UserRiskProfileCreate) SetLockReason(v string) *UserRiskProfileCreate {
	_c.mutation.SetLockReason(v)
	return _c
}

// SetNillableLockReason sets the "lock_reason" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableLockReason(v *string) *UserRiskProfileCreate {
	if v != nil {
		_c.SetLockReason(*v)
	}
	return _c
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (_c *UserRiskProfileCreate) SetLastEvaluationSummary(v string) *UserRiskProfileCreate {
	_c.mutation.SetLastEvaluationSummary(v)
	return _c
}

// SetNillableLastEvaluationSummary sets the "last_evaluation_summary" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableLastEvaluationSummary(v *string) *UserRiskProfileCreate {
	if v != nil {
		_c.SetLastEvaluationSummary(*v)
	}
	return _c
}

// SetExempted sets the "exempted" field.
func (_c *UserRiskProfileCreate) SetExempted(v bool) *UserRiskProfileCreate {
	_c.mutation.SetExempted(v)
	return _c
}

// SetNillableExempted sets the "exempted" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableExempted(v *bool) *UserRiskProfileCreate {
	if v != nil {
		_c.SetExempted(*v)
	}
	return _c
}

// SetExemptedAt sets the "exempted_at" field.
func (_c *UserRiskProfileCreate) SetExemptedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetExemptedAt(v)
	return _c
}

// SetNillableExemptedAt sets the "exempted_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableExemptedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetExemptedAt(*v)
	}
	return _c
}

// SetExemptedBy sets the "exempted_by" field.
func (_c *UserRiskProfileCreate) SetExemptedBy(v int64) *UserRiskProfileCreate {
	_c.mutation.SetExemptedBy(v)
	return _c
}

// SetNillableExemptedBy sets the "exempted_by" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableExemptedBy(v *int64) *UserRiskProfileCreate {
	if v != nil {
		_c.SetExemptedBy(*v)
	}
	return _c
}

// SetExemptionReason sets the "exemption_reason" field.
func (_c *UserRiskProfileCreate) SetExemptionReason(v string) *UserRiskProfileCreate {
	_c.mutation.SetExemptionReason(v)
	return _c
}

// SetNillableExemptionReason sets the "exemption_reason" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableExemptionReason(v *string) *UserRiskProfileCreate {
	if v != nil {
		_c.SetExemptionReason(*v)
	}
	return _c
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_c *UserRiskProfileCreate) SetUnlockedAt(v time.Time) *UserRiskProfileCreate {
	_c.mutation.SetUnlockedAt(v)
	return _c
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableUnlockedAt(v *time.Time) *UserRiskProfileCreate {
	if v != nil {
		_c.SetUnlockedAt(*v)
	}
	return _c
}

// SetUnlockedBy sets the "unlocked_by" field.
func (_c *UserRiskProfileCreate) SetUnlockedBy(v int64) *UserRiskProfileCreate {
	_c.mutation.SetUnlockedBy(v)
	return _c
}

// SetNillableUnlockedBy sets the "unlocked_by" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableUnlockedBy(v *int64) *UserRiskProfileCreate {
	if v != nil {
		_c.SetUnlockedBy(*v)
	}
	return _c
}

// SetUnlockReason sets the "unlock_reason" field.
func (_c *UserRiskProfileCreate) SetUnlockReason(v string) *UserRiskProfileCreate {
	_c.mutation.SetUnlockReason(v)
	return _c
}

// SetNillableUnlockReason sets the "unlock_reason" field if the given value is not nil.
func (_c *UserRiskProfileCreate) SetNillableUnlockReason(v *string) *UserRiskProfileCreate {
	if v != nil {
		_c.SetUnlockReason(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserRiskProfileCreate) SetUser(v *User) *UserRiskProfileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserRiskProfileMutation object of the builder.
func (_c *UserRiskProfileCreate) Mutation() *UserRiskProfileMutation {
	return _c.mutation
}

// Save creates the UserRiskProfile in the database.
func (_c *UserRiskProfileCreate) Save(ctx context.Context) (*UserRiskProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRiskProfileCreate) SaveX(ctx context.Context) *UserRiskProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRiskProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRiskProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRiskProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userriskprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userriskprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Score(); !ok {
		v := userriskprofile.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userriskprofile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ConsecutiveBadDays(); !ok {
		v := userriskprofile.DefaultConsecutiveBadDays
		_c.mutation.SetConsecutiveBadDays(v)
	}
	if _, ok := _c.mutation.LockReason(); !ok {
		v := userriskprofile.DefaultLockReason
		_c.mutation.SetLockReason(v)
	}
	if _, ok := _c.mutation.LastEvaluationSummary(); !ok {
		v := userriskprofile.DefaultLastEvaluationSummary
		_c.mutation.SetLastEvaluationSummary(v)
	}
	if _, ok := _c.mutation.Exempted(); !ok {
		v := userriskprofile.DefaultExempted
		_c.mutation.SetExempted(v)
	}
	if _, ok := _c.mutation.ExemptionReason(); !ok {
		v := userriskprofile.DefaultExemptionReason
		_c.mutation.SetExemptionReason(v)
	}
	if _, ok := _c.mutation.UnlockReason(); !ok {
		v := userriskprofile.DefaultUnlockReason
		_c.mutation.SetUnlockReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRiskProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRiskProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRiskProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRiskProfile.user_id"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "UserRiskProfile.score"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserRiskProfile.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userriskprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRiskProfile.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConsecutiveBadDays(); !ok {
		return &ValidationError{Name: "consecutive_bad_days", err: errors.New(`ent: missing required field "UserRiskProfile.consecutive_bad_days"`)}
	}
	if _, ok := _c.mutation.LockReason(); !ok {
		return &ValidationError{Name: "lock_reason", err: errors.New(`ent: missing required field "UserRiskProfile.lock_reason"`)}
	}
	if _, ok := _c.mutation.LastEvaluationSummary(); !ok {
		return &ValidationError{Name: "last_evaluation_summary", err: errors.New(`ent: missing required field "UserRiskProfile.last_evaluation_summary"`)}
	}
	if _, ok := _c.mutation.Exempted(); !ok {
		return &ValidationError{Name: "exempted", err: errors.New(`ent: missing required field "UserRiskProfile.exempted"`)}
	}
	if _, ok := _c.mutation.ExemptionReason(); !ok {
		return &ValidationError{Name: "exemption_reason", err: errors.New(`ent: missing required field "UserRiskProfile.exemption_reason"`)}
	}
	if _, ok := _c.mutation.UnlockReason(); !ok {
		return &ValidationError{Name: "unlock_reason", err: errors.New(`ent: missing required field "UserRiskProfile.unlock_reason"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserRiskProfile.user"`)}
	}
	return nil
}

func (_c *UserRiskProfileCreate) sqlSave(ctx context.Context) (*UserRiskProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRiskProfileCreate) createSpec() (*UserRiskProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRiskProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userriskprofile.Table, sqlgraph.NewFieldSpec(userriskprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userriskprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(userriskprofile.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userriskprofile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ConsecutiveBadDays(); ok {
		_spec.SetField(userriskprofile.FieldConsecutiveBadDays, field.TypeInt, value)
		_node.ConsecutiveBadDays = value
	}
	if value, ok := _c.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluatedAt, field.TypeTime, value)
		_node.LastEvaluatedAt = &value
	}
	if value, ok := _c.mutation.LastWarnedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastWarnedAt, field.TypeTime, value)
		_node.LastWarnedAt = &value
	}
	if value, ok := _c.mutation.GracePeriodStartedAt(); ok {
		_spec.SetField(userriskprofile.FieldGracePeriodStartedAt, field.TypeTime, value)
		_node.GracePeriodStartedAt = &value
	}
	if value, ok := _c.mutation.LockedAt(); ok {
		_spec.SetField(userriskprofile.FieldLockedAt, field.TypeTime, value)
		_node.LockedAt = &value
	}
	if value, ok := _c.mutation.LockReason(); ok {
		_spec.SetField(userriskprofile.FieldLockReason, field.TypeString, value)
		_node.LockReason = value
	}
	if value, ok := _c.mutation.LastEvaluationSummary(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluationSummary, field.TypeString, value)
		_node.LastEvaluationSummary = value
	}
	if value, ok := _c.mutation.Exempted(); ok {
		_spec.SetField(userriskprofile.FieldExempted, field.TypeBool, value)
		_node.Exempted = value
	}
	if value, ok := _c.mutation.ExemptedAt(); ok {
		_spec.SetField(userriskprofile.FieldExemptedAt, field.TypeTime, value)
		_node.ExemptedAt = &value
	}
	if value, ok := _c.mutation.ExemptedBy(); ok {
		_spec.SetField(userriskprofile.FieldExemptedBy, field.TypeInt64, value)
		_node.ExemptedBy = &value
	}
	if value, ok := _c.mutation.ExemptionReason(); ok {
		_spec.SetField(userriskprofile.FieldExemptionReason, field.TypeString, value)
		_node.ExemptionReason = value
	}
	if value, ok := _c.mutation.UnlockedAt(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedAt, field.TypeTime, value)
		_node.UnlockedAt = &value
	}
	if value, ok := _c.mutation.UnlockedBy(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedBy, field.TypeInt64, value)
		_node.UnlockedBy = &value
	}
	if value, ok := _c.mutation.UnlockReason(); ok {
		_spec.SetField(userriskprofile.FieldUnlockReason, field.TypeString, value)
		_node.UnlockReason = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userriskprofile.UserTable,
			Columns: []string{userriskprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRiskProfile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRiskProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRiskProfileCreate) OnConflict(opts ...sql.ConflictOption) *UserRiskProfileUpsertOne {
	_c.conflict = opts
	return &UserRiskProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRiskProfileCreate) OnConflictColumns(columns ...string) *UserRiskProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRiskProfileUpsertOne{
		create: _c,
	}
}

type (
	// UserRiskProfileUpsertOne is the builder for "upsert"-ing
	//  one UserRiskProfile node.
	UserRiskProfileUpsertOne struct {
		create *UserRiskProfileCreate
	}

	// UserRiskProfileUpsert is the "OnConflict" setter.
	UserRiskProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskProfileUpsert) SetUpdatedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateUpdatedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRiskProfileUpsert) SetUserID(v int64) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateUserID() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldUserID)
	return u
}

// SetScore sets the "score" field.
func (u *UserRiskProfileUpsert) SetScore(v float64) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateScore() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *UserRiskProfileUpsert) AddScore(v float64) *UserRiskProfileUpsert {
	u.Add(userriskprofile.FieldScore, v)
	return u
}

// SetStatus sets the "status" field.
func (u *UserRiskProfileUpsert) SetStatus(v string) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateStatus() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldStatus)
	return u
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsert) SetConsecutiveBadDays(v int) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldConsecutiveBadDays, v)
	return u
}

// UpdateConsecutiveBadDays sets the "consecutive_bad_days" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateConsecutiveBadDays() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldConsecutiveBadDays)
	return u
}

// AddConsecutiveBadDays adds v to the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsert) AddConsecutiveBadDays(v int) *UserRiskProfileUpsert {
	u.Add(userriskprofile.FieldConsecutiveBadDays, v)
	return u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserRiskProfileUpsert) SetLastEvaluatedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldLastEvaluatedAt, v)
	return u
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateLastEvaluatedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldLastEvaluatedAt)
	return u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserRiskProfileUpsert) ClearLastEvaluatedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldLastEvaluatedAt)
	return u
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (u *UserRiskProfileUpsert) SetLastWarnedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldLastWarnedAt, v)
	return u
}

// UpdateLastWarnedAt sets the "last_warned_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateLastWarnedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldLastWarnedAt)
	return u
}

// ClearLastWarnedAt clears the value of the "last_warned_at" field.
func (u *UserRiskProfileUpsert) ClearLastWarnedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldLastWarnedAt)
	return u
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (u *UserRiskProfileUpsert) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldGracePeriodStartedAt, v)
	return u
}

// UpdateGracePeriodStartedAt sets the "grace_period_started_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateGracePeriodStartedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldGracePeriodStartedAt)
	return u
}

// ClearGracePeriodStartedAt clears the value of the "grace_period_started_at" field.
func (u *UserRiskProfileUpsert) ClearGracePeriodStartedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldGracePeriodStartedAt)
	return u
}

// SetLockedAt sets the "locked_at" field.
func (u *UserRiskProfileUpsert) SetLockedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldLockedAt, v)
	return u
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateLockedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldLockedAt)
	return u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *UserRiskProfileUpsert) ClearLockedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldLockedAt)
	return u
}

// SetLockReason sets the "lock_reason" field.
func (u *UserRiskProfileUpsert) SetLockReason(v string) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldLockReason, v)
	return u
}

// UpdateLockReason sets the "lock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateLockReason() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldLockReason)
	return u
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (u *UserRiskProfileUpsert) SetLastEvaluationSummary(v string) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldLastEvaluationSummary, v)
	return u
}

// UpdateLastEvaluationSummary sets the "last_evaluation_summary" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateLastEvaluationSummary() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldLastEvaluationSummary)
	return u
}

// SetExempted sets the "exempted" field.
func (u *UserRiskProfileUpsert) SetExempted(v bool) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldExempted, v)
	return u
}

// UpdateExempted sets the "exempted" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateExempted() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldExempted)
	return u
}

// SetExemptedAt sets the "exempted_at" field.
func (u *UserRiskProfileUpsert) SetExemptedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldExemptedAt, v)
	return u
}

// UpdateExemptedAt sets the "exempted_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateExemptedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldExemptedAt)
	return u
}

// ClearExemptedAt clears the value of the "exempted_at" field.
func (u *UserRiskProfileUpsert) ClearExemptedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldExemptedAt)
	return u
}

// SetExemptedBy sets the "exempted_by" field.
func (u *UserRiskProfileUpsert) SetExemptedBy(v int64) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldExemptedBy, v)
	return u
}

// UpdateExemptedBy sets the "exempted_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateExemptedBy() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldExemptedBy)
	return u
}

// AddExemptedBy adds v to the "exempted_by" field.
func (u *UserRiskProfileUpsert) AddExemptedBy(v int64) *UserRiskProfileUpsert {
	u.Add(userriskprofile.FieldExemptedBy, v)
	return u
}

// ClearExemptedBy clears the value of the "exempted_by" field.
func (u *UserRiskProfileUpsert) ClearExemptedBy() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldExemptedBy)
	return u
}

// SetExemptionReason sets the "exemption_reason" field.
func (u *UserRiskProfileUpsert) SetExemptionReason(v string) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldExemptionReason, v)
	return u
}

// UpdateExemptionReason sets the "exemption_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateExemptionReason() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldExemptionReason)
	return u
}

// SetUnlockedAt sets the "unlocked_at" field.
func (u *UserRiskProfileUpsert) SetUnlockedAt(v time.Time) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldUnlockedAt, v)
	return u
}

// UpdateUnlockedAt sets the "unlocked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateUnlockedAt() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldUnlockedAt)
	return u
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (u *UserRiskProfileUpsert) ClearUnlockedAt() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldUnlockedAt)
	return u
}

// SetUnlockedBy sets the "unlocked_by" field.
func (u *UserRiskProfileUpsert) SetUnlockedBy(v int64) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldUnlockedBy, v)
	return u
}

// UpdateUnlockedBy sets the "unlocked_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateUnlockedBy() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldUnlockedBy)
	return u
}

// AddUnlockedBy adds v to the "unlocked_by" field.
func (u *UserRiskProfileUpsert) AddUnlockedBy(v int64) *UserRiskProfileUpsert {
	u.Add(userriskprofile.FieldUnlockedBy, v)
	return u
}

// ClearUnlockedBy clears the value of the "unlocked_by" field.
func (u *UserRiskProfileUpsert) ClearUnlockedBy() *UserRiskProfileUpsert {
	u.SetNull(userriskprofile.FieldUnlockedBy)
	return u
}

// SetUnlockReason sets the "unlock_reason" field.
func (u *UserRiskProfileUpsert) SetUnlockReason(v string) *UserRiskProfileUpsert {
	u.Set(userriskprofile.FieldUnlockReason, v)
	return u
}

// UpdateUnlockReason sets the "unlock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsert) UpdateUnlockReason() *UserRiskProfileUpsert {
	u.SetExcluded(userriskprofile.FieldUnlockReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRiskProfileUpsertOne) UpdateNewValues() *UserRiskProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userriskprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRiskProfileUpsertOne) Ignore() *UserRiskProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRiskProfileUpsertOne) DoNothing() *UserRiskProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRiskProfileCreate.OnConflict
// documentation for more info.
func (u *UserRiskProfileUpsertOne) Update(set func(*UserRiskProfileUpsert)) *UserRiskProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRiskProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskProfileUpsertOne) SetUpdatedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateUpdatedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRiskProfileUpsertOne) SetUserID(v int64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateUserID() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetScore sets the "score" field.
func (u *UserRiskProfileUpsertOne) SetScore(v float64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *UserRiskProfileUpsertOne) AddScore(v float64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateScore() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateScore()
	})
}

// SetStatus sets the "status" field.
func (u *UserRiskProfileUpsertOne) SetStatus(v string) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateStatus() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateStatus()
	})
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsertOne) SetConsecutiveBadDays(v int) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetConsecutiveBadDays(v)
	})
}

// AddConsecutiveBadDays adds v to the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsertOne) AddConsecutiveBadDays(v int) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddConsecutiveBadDays(v)
	})
}

// UpdateConsecutiveBadDays sets the "consecutive_bad_days" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateConsecutiveBadDays() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateConsecutiveBadDays()
	})
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserRiskProfileUpsertOne) SetLastEvaluatedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastEvaluatedAt(v)
	})
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateLastEvaluatedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastEvaluatedAt()
	})
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserRiskProfileUpsertOne) ClearLastEvaluatedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLastEvaluatedAt()
	})
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (u *UserRiskProfileUpsertOne) SetLastWarnedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastWarnedAt(v)
	})
}

// UpdateLastWarnedAt sets the "last_warned_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateLastWarnedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastWarnedAt()
	})
}

// ClearLastWarnedAt clears the value of the "last_warned_at" field.
func (u *UserRiskProfileUpsertOne) ClearLastWarnedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLastWarnedAt()
	})
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (u *UserRiskProfileUpsertOne) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetGracePeriodStartedAt(v)
	})
}

// UpdateGracePeriodStartedAt sets the "grace_period_started_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateGracePeriodStartedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateGracePeriodStartedAt()
	})
}

// ClearGracePeriodStartedAt clears the value of the "grace_period_started_at" field.
func (u *UserRiskProfileUpsertOne) ClearGracePeriodStartedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearGracePeriodStartedAt()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *UserRiskProfileUpsertOne) SetLockedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateLockedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *UserRiskProfileUpsertOne) ClearLockedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockReason sets the "lock_reason" field.
func (u *UserRiskProfileUpsertOne) SetLockReason(v string) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLockReason(v)
	})
}

// UpdateLockReason sets the "lock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateLockReason() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLockReason()
	})
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (u *UserRiskProfileUpsertOne) SetLastEvaluationSummary(v string) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastEvaluationSummary(v)
	})
}

// UpdateLastEvaluationSummary sets the "last_evaluation_summary" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateLastEvaluationSummary() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastEvaluationSummary()
	})
}

// SetExempted sets the "exempted" field.
func (u *UserRiskProfileUpsertOne) SetExempted(v bool) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExempted(v)
	})
}

// UpdateExempted sets the "exempted" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateExempted() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExempted()
	})
}

// SetExemptedAt sets the "exempted_at" field.
func (u *UserRiskProfileUpsertOne) SetExemptedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptedAt(v)
	})
}

// UpdateExemptedAt sets the "exempted_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateExemptedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptedAt()
	})
}

// ClearExemptedAt clears the value of the "exempted_at" field.
func (u *UserRiskProfileUpsertOne) ClearExemptedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearExemptedAt()
	})
}

// SetExemptedBy sets the "exempted_by" field.
func (u *UserRiskProfileUpsertOne) SetExemptedBy(v int64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptedBy(v)
	})
}

// AddExemptedBy adds v to the "exempted_by" field.
func (u *UserRiskProfileUpsertOne) AddExemptedBy(v int64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddExemptedBy(v)
	})
}

// UpdateExemptedBy sets the "exempted_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateExemptedBy() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptedBy()
	})
}

// ClearExemptedBy clears the value of the "exempted_by" field.
func (u *UserRiskProfileUpsertOne) ClearExemptedBy() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearExemptedBy()
	})
}

// SetExemptionReason sets the "exemption_reason" field.
func (u *UserRiskProfileUpsertOne) SetExemptionReason(v string) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptionReason(v)
	})
}

// UpdateExemptionReason sets the "exemption_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateExemptionReason() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptionReason()
	})
}

// SetUnlockedAt sets the "unlocked_at" field.
func (u *UserRiskProfileUpsertOne) SetUnlockedAt(v time.Time) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockedAt(v)
	})
}

// UpdateUnlockedAt sets the "unlocked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateUnlockedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockedAt()
	})
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (u *UserRiskProfileUpsertOne) ClearUnlockedAt() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearUnlockedAt()
	})
}

// SetUnlockedBy sets the "unlocked_by" field.
func (u *UserRiskProfileUpsertOne) SetUnlockedBy(v int64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockedBy(v)
	})
}

// AddUnlockedBy adds v to the "unlocked_by" field.
func (u *UserRiskProfileUpsertOne) AddUnlockedBy(v int64) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddUnlockedBy(v)
	})
}

// UpdateUnlockedBy sets the "unlocked_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateUnlockedBy() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockedBy()
	})
}

// ClearUnlockedBy clears the value of the "unlocked_by" field.
func (u *UserRiskProfileUpsertOne) ClearUnlockedBy() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearUnlockedBy()
	})
}

// SetUnlockReason sets the "unlock_reason" field.
func (u *UserRiskProfileUpsertOne) SetUnlockReason(v string) *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockReason(v)
	})
}

// UpdateUnlockReason sets the "unlock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertOne) UpdateUnlockReason() *UserRiskProfileUpsertOne {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockReason()
	})
}

// Exec executes the query.
func (u *UserRiskProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRiskProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRiskProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRiskProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRiskProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRiskProfileCreateBulk is the builder for creating many UserRiskProfile entities in bulk.
type UserRiskProfileCreateBulk struct {
	config
	err      error
	builders []*UserRiskProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRiskProfile entities in the database.
func (_c *UserRiskProfileCreateBulk) Save(ctx context.Context) ([]*UserRiskProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRiskProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRiskProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRiskProfileCreateBulk) SaveX(ctx context.Context) []*UserRiskProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRiskProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRiskProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRiskProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRiskProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRiskProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRiskProfileUpsertBulk {
	_c.conflict = opts
	return &UserRiskProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRiskProfileCreateBulk) OnConflictColumns(columns ...string) *UserRiskProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRiskProfileUpsertBulk{
		create: _c,
	}
}

// UserRiskProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRiskProfile nodes.
type UserRiskProfileUpsertBulk struct {
	create *UserRiskProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRiskProfileUpsertBulk) UpdateNewValues() *UserRiskProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userriskprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRiskProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRiskProfileUpsertBulk) Ignore() *UserRiskProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRiskProfileUpsertBulk) DoNothing() *UserRiskProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRiskProfileCreateBulk.OnConflict
// documentation for more info.
func (u *UserRiskProfileUpsertBulk) Update(set func(*UserRiskProfileUpsert)) *UserRiskProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRiskProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRiskProfileUpsertBulk) SetUpdatedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateUpdatedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRiskProfileUpsertBulk) SetUserID(v int64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateUserID() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetScore sets the "score" field.
func (u *UserRiskProfileUpsertBulk) SetScore(v float64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *UserRiskProfileUpsertBulk) AddScore(v float64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateScore() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateScore()
	})
}

// SetStatus sets the "status" field.
func (u *UserRiskProfileUpsertBulk) SetStatus(v string) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateStatus() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateStatus()
	})
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsertBulk) SetConsecutiveBadDays(v int) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetConsecutiveBadDays(v)
	})
}

// AddConsecutiveBadDays adds v to the "consecutive_bad_days" field.
func (u *UserRiskProfileUpsertBulk) AddConsecutiveBadDays(v int) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddConsecutiveBadDays(v)
	})
}

// UpdateConsecutiveBadDays sets the "consecutive_bad_days" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateConsecutiveBadDays() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateConsecutiveBadDays()
	})
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserRiskProfileUpsertBulk) SetLastEvaluatedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastEvaluatedAt(v)
	})
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateLastEvaluatedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastEvaluatedAt()
	})
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserRiskProfileUpsertBulk) ClearLastEvaluatedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLastEvaluatedAt()
	})
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (u *UserRiskProfileUpsertBulk) SetLastWarnedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastWarnedAt(v)
	})
}

// UpdateLastWarnedAt sets the "last_warned_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateLastWarnedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastWarnedAt()
	})
}

// ClearLastWarnedAt clears the value of the "last_warned_at" field.
func (u *UserRiskProfileUpsertBulk) ClearLastWarnedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLastWarnedAt()
	})
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (u *UserRiskProfileUpsertBulk) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetGracePeriodStartedAt(v)
	})
}

// UpdateGracePeriodStartedAt sets the "grace_period_started_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateGracePeriodStartedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateGracePeriodStartedAt()
	})
}

// ClearGracePeriodStartedAt clears the value of the "grace_period_started_at" field.
func (u *UserRiskProfileUpsertBulk) ClearGracePeriodStartedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearGracePeriodStartedAt()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *UserRiskProfileUpsertBulk) SetLockedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateLockedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *UserRiskProfileUpsertBulk) ClearLockedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockReason sets the "lock_reason" field.
func (u *UserRiskProfileUpsertBulk) SetLockReason(v string) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLockReason(v)
	})
}

// UpdateLockReason sets the "lock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateLockReason() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLockReason()
	})
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (u *UserRiskProfileUpsertBulk) SetLastEvaluationSummary(v string) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetLastEvaluationSummary(v)
	})
}

// UpdateLastEvaluationSummary sets the "last_evaluation_summary" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateLastEvaluationSummary() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateLastEvaluationSummary()
	})
}

// SetExempted sets the "exempted" field.
func (u *UserRiskProfileUpsertBulk) SetExempted(v bool) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExempted(v)
	})
}

// UpdateExempted sets the "exempted" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateExempted() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExempted()
	})
}

// SetExemptedAt sets the "exempted_at" field.
func (u *UserRiskProfileUpsertBulk) SetExemptedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptedAt(v)
	})
}

// UpdateExemptedAt sets the "exempted_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateExemptedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptedAt()
	})
}

// ClearExemptedAt clears the value of the "exempted_at" field.
func (u *UserRiskProfileUpsertBulk) ClearExemptedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearExemptedAt()
	})
}

// SetExemptedBy sets the "exempted_by" field.
func (u *UserRiskProfileUpsertBulk) SetExemptedBy(v int64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptedBy(v)
	})
}

// AddExemptedBy adds v to the "exempted_by" field.
func (u *UserRiskProfileUpsertBulk) AddExemptedBy(v int64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddExemptedBy(v)
	})
}

// UpdateExemptedBy sets the "exempted_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateExemptedBy() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptedBy()
	})
}

// ClearExemptedBy clears the value of the "exempted_by" field.
func (u *UserRiskProfileUpsertBulk) ClearExemptedBy() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearExemptedBy()
	})
}

// SetExemptionReason sets the "exemption_reason" field.
func (u *UserRiskProfileUpsertBulk) SetExemptionReason(v string) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetExemptionReason(v)
	})
}

// UpdateExemptionReason sets the "exemption_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateExemptionReason() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateExemptionReason()
	})
}

// SetUnlockedAt sets the "unlocked_at" field.
func (u *UserRiskProfileUpsertBulk) SetUnlockedAt(v time.Time) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockedAt(v)
	})
}

// UpdateUnlockedAt sets the "unlocked_at" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateUnlockedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockedAt()
	})
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (u *UserRiskProfileUpsertBulk) ClearUnlockedAt() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearUnlockedAt()
	})
}

// SetUnlockedBy sets the "unlocked_by" field.
func (u *UserRiskProfileUpsertBulk) SetUnlockedBy(v int64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockedBy(v)
	})
}

// AddUnlockedBy adds v to the "unlocked_by" field.
func (u *UserRiskProfileUpsertBulk) AddUnlockedBy(v int64) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.AddUnlockedBy(v)
	})
}

// UpdateUnlockedBy sets the "unlocked_by" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateUnlockedBy() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockedBy()
	})
}

// ClearUnlockedBy clears the value of the "unlocked_by" field.
func (u *UserRiskProfileUpsertBulk) ClearUnlockedBy() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.ClearUnlockedBy()
	})
}

// SetUnlockReason sets the "unlock_reason" field.
func (u *UserRiskProfileUpsertBulk) SetUnlockReason(v string) *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.SetUnlockReason(v)
	})
}

// UpdateUnlockReason sets the "unlock_reason" field to the value that was provided on create.
func (u *UserRiskProfileUpsertBulk) UpdateUnlockReason() *UserRiskProfileUpsertBulk {
	return u.Update(func(s *UserRiskProfileUpsert) {
		s.UpdateUnlockReason()
	})
}

// Exec executes the query.
func (u *UserRiskProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRiskProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRiskProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRiskProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
