// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskevent"
)

// UserRiskEventUpdate is the builder for updating UserRiskEvent entities.
type UserRiskEventUpdate struct {
	config
	hooks    []Hook
	mutation *UserRiskEventMutation
}

// Where appends a list predicates to the UserRiskEventUpdate builder.
func (_u *UserRiskEventUpdate) Where(ps ...predicate.UserRiskEvent) *UserRiskEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRiskEventUpdate) SetUpdatedAt(v time.Time) *UserRiskEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRiskEventUpdate) SetUserID(v int64) *UserRiskEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableUserID(v *int64) *UserRiskEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *UserRiskEventUpdate) SetEventType(v string) *UserRiskEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableEventType(v *string) *UserRiskEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *UserRiskEventUpdate) SetSeverity(v string) *UserRiskEventUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableSeverity(v *string) *UserRiskEventUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetScoreDelta sets the "score_delta" field.
func (_u *UserRiskEventUpdate) SetScoreDelta(v float64) *UserRiskEventUpdate {
	_u.mutation.ResetScoreDelta()
	_u.mutation.SetScoreDelta(v)
	return _u
}

// SetNillableScoreDelta sets the "score_delta" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableScoreDelta(v *float64) *UserRiskEventUpdate {
	if v != nil {
		_u.SetScoreDelta(*v)
	}
	return _u
}

// AddScoreDelta adds value to the "score_delta" field.
func (_u *UserRiskEventUpdate) AddScoreDelta(v float64) *UserRiskEventUpdate {
	_u.mutation.AddScoreDelta(v)
	return _u
}

// SetScoreAfter sets the "score_after" field.
func (_u *UserRiskEventUpdate) SetScoreAfter(v float64) *UserRiskEventUpdate {
	_u.mutation.ResetScoreAfter()
	_u.mutation.SetScoreAfter(v)
	return _u
}

// SetNillableScoreAfter sets the "score_after" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableScoreAfter(v *float64) *UserRiskEventUpdate {
	if v != nil {
		_u.SetScoreAfter(*v)
	}
	return _u
}

// AddScoreAfter adds value to the "score_after" field.
func (_u *UserRiskEventUpdate) AddScoreAfter(v float64) *UserRiskEventUpdate {
	_u.mutation.AddScoreAfter(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *UserRiskEventUpdate) SetSummary(v string) *UserRiskEventUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableSummary(v *string) *UserRiskEventUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserRiskEventUpdate) SetMetadata(v map[string]interface{}) *UserRiskEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserRiskEventUpdate) ClearMetadata() *UserRiskEventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *UserRiskEventUpdate) SetWindowStart(v time.Time) *UserRiskEventUpdate {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableWindowStart(v *time.Time) *UserRiskEventUpdate {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// ClearWindowStart clears the value of the "window_start" field.
func (_u *UserRiskEventUpdate) ClearWindowStart() *UserRiskEventUpdate {
	_u.mutation.ClearWindowStart()
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *UserRiskEventUpdate) SetWindowEnd(v time.Time) *UserRiskEventUpdate {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *UserRiskEventUpdate) SetNillableWindowEnd(v *time.Time) *UserRiskEventUpdate {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (_u *UserRiskEventUpdate) ClearWindowEnd() *UserRiskEventUpdate {
	_u.mutation.ClearWindowEnd()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRiskEventUpdate) SetUser(v *User) *UserRiskEventUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRiskEventMutation object of the builder.
func (_u *UserRiskEventUpdate) Mutation() *UserRiskEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRiskEventUpdate) ClearUser() *UserRiskEventUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRiskEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRiskEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRiskEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRiskEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRiskEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userriskevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRiskEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := userriskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := userriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.severity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRiskEvent.user"`)
	}
	return nil
}

func (_u *UserRiskEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userriskevent.Table, userriskevent.Columns, sqlgraph.NewFieldSpec(userriskevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(userriskevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(userriskevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoreDelta(); ok {
		_spec.SetField(userriskevent.FieldScoreDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScoreDelta(); ok {
		_spec.AddField(userriskevent.FieldScoreDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ScoreAfter(); ok {
		_spec.SetField(userriskevent.FieldScoreAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScoreAfter(); ok {
		_spec.AddField(userriskevent.FieldScoreAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(userriskevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(userriskevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(userriskevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(userriskevent.FieldWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WindowStartCleared() {
		_spec.ClearField(userriskevent.FieldWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(userriskevent.FieldWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.WindowEndCleared() {
		_spec.ClearField(userriskevent.FieldWindowEnd, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userriskevent.UserTable,
			Columns: []string{userriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userriskevent.UserTable,
			Columns: []string{userriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userriskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRiskEventUpdateOne is the builder for updating a single UserRiskEvent entity.
type UserRiskEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRiskEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRiskEventUpdateOne) SetUpdatedAt(v time.Time) *UserRiskEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRiskEventUpdateOne) SetUserID(v int64) *UserRiskEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableUserID(v *int64) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *UserRiskEventUpdateOne) SetEventType(v string) *UserRiskEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableEventType(v *string) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *UserRiskEventUpdateOne) SetSeverity(v string) *UserRiskEventUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableSeverity(v *string) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetScoreDelta sets the "score_delta" field.
func (_u *UserRiskEventUpdateOne) SetScoreDelta(v float64) *UserRiskEventUpdateOne {
	_u.mutation.ResetScoreDelta()
	_u.mutation.SetScoreDelta(v)
	return _u
}

// SetNillableScoreDelta sets the "score_delta" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableScoreDelta(v *float64) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetScoreDelta(*v)
	}
	return _u
}

// AddScoreDelta adds value to the "score_delta" field.
func (_u *UserRiskEventUpdateOne) AddScoreDelta(v float64) *UserRiskEventUpdateOne {
	_u.mutation.AddScoreDelta(v)
	return _u
}

// SetScoreAfter sets the "score_after" field.
func (_u *UserRiskEventUpdateOne) SetScoreAfter(v float64) *UserRiskEventUpdateOne {
	_u.mutation.ResetScoreAfter()
	_u.mutation.SetScoreAfter(v)
	return _u
}

// SetNillableScoreAfter sets the "score_after" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableScoreAfter(v *float64) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetScoreAfter(*v)
	}
	return _u
}

// AddScoreAfter adds value to the "score_after" field.
func (_u *UserRiskEventUpdateOne) AddScoreAfter(v float64) *UserRiskEventUpdateOne {
	_u.mutation.AddScoreAfter(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *UserRiskEventUpdateOne) SetSummary(v string) *UserRiskEventUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableSummary(v *string) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserRiskEventUpdateOne) SetMetadata(v map[string]interface{}) *UserRiskEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserRiskEventUpdateOne) ClearMetadata() *UserRiskEventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *UserRiskEventUpdateOne) SetWindowStart(v time.Time) *UserRiskEventUpdateOne {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableWindowStart(v *time.Time) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// ClearWindowStart clears the value of the "window_start" field.
func (_u *UserRiskEventUpdateOne) ClearWindowStart() *UserRiskEventUpdateOne {
	_u.mutation.ClearWindowStart()
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *UserRiskEventUpdateOne) SetWindowEnd(v time.Time) *UserRiskEventUpdateOne {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *UserRiskEventUpdateOne) SetNillableWindowEnd(v *time.Time) *UserRiskEventUpdateOne {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (_u *UserRiskEventUpdateOne) ClearWindowEnd() *UserRiskEventUpdateOne {
	_u.mutation.ClearWindowEnd()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRiskEventUpdateOne) SetUser(v *User) *UserRiskEventUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRiskEventMutation object of the builder.
func (_u *UserRiskEventUpdateOne) Mutation() *UserRiskEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRiskEventUpdateOne) ClearUser() *UserRiskEventUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserRiskEventUpdate builder.
func (_u *UserRiskEventUpdateOne) Where(ps ...predicate.UserRiskEvent) *UserRiskEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRiskEventUpdateOne) Select(field string, fields ...string) *UserRiskEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRiskEvent entity.
func (_u *UserRiskEventUpdateOne) Save(ctx context.Context) (*UserRiskEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRiskEventUpdateOne) SaveX(ctx context.Context) *UserRiskEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRiskEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRiskEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRiskEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userriskevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRiskEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := userriskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := userriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "UserRiskEvent.severity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRiskEvent.user"`)
	}
	return nil
}

func (_u *UserRiskEventUpdateOne) sqlSave(ctx context.Context) (_node *UserRiskEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userriskevent.Table, userriskevent.Columns, sqlgraph.NewFieldSpec(userriskevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRiskEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userriskevent.FieldID)
		for _, f := range fields {
			if !userriskevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userriskevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(userriskevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(userriskevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoreDelta(); ok {
		_spec.SetField(userriskevent.FieldScoreDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScoreDelta(); ok {
		_spec.AddField(userriskevent.FieldScoreDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ScoreAfter(); ok {
		_spec.SetField(userriskevent.FieldScoreAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScoreAfter(); ok {
		_spec.AddField(userriskevent.FieldScoreAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(userriskevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(userriskevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(userriskevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(userriskevent.FieldWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WindowStartCleared() {
		_spec.ClearField(userriskevent.FieldWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(userriskevent.FieldWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.WindowEndCleared() {
		_spec.ClearField(userriskevent.FieldWindowEnd, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userriskevent.UserTable,
			Columns: []string{userriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userriskevent.UserTable,
			Columns: []string{userriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRiskEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userriskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
