// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskevent"
)

// UserRiskEvent is the model entity for the UserRiskEvent schema.
type UserRiskEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// ScoreDelta holds the value of the "score_delta" field.
	ScoreDelta float64 `json:"score_delta,omitempty"`
	// ScoreAfter holds the value of the "score_after" field.
	ScoreAfter float64 `json:"score_after,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// WindowStart holds the value of the "window_start" field.
	WindowStart *time.Time `json:"window_start,omitempty"`
	// WindowEnd holds the value of the "window_end" field.
	WindowEnd *time.Time `json:"window_end,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserRiskEventQuery when eager-loading is set.
	Edges        UserRiskEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserRiskEventEdges holds the relations/edges for other nodes in the graph.
type UserRiskEventEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserRiskEventEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserRiskEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userriskevent.FieldMetadata:
			values[i] = new([]byte)
		case userriskevent.FieldScoreDelta, userriskevent.FieldScoreAfter:
			values[i] = new(sql.NullFloat64)
		case userriskevent.FieldID, userriskevent.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userriskevent.FieldEventType, userriskevent.FieldSeverity, userriskevent.FieldSummary:
			values[i] = new(sql.NullString)
		case userriskevent.FieldCreatedAt, userriskevent.FieldUpdatedAt, userriskevent.FieldWindowStart, userriskevent.FieldWindowEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserRiskEvent fields.
func (_m *UserRiskEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userriskevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userriskevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userriskevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userriskevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userriskevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case userriskevent.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case userriskevent.FieldScoreDelta:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score_delta", values[i])
			} else if value.Valid {
				_m.ScoreDelta = value.Float64
			}
		case userriskevent.FieldScoreAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score_after", values[i])
			} else if value.Valid {
				_m.ScoreAfter = value.Float64
			}
		case userriskevent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case userriskevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case userriskevent.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = new(time.Time)
				*_m.WindowStart = value.Time
			}
		case userriskevent.FieldWindowEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_end", values[i])
			} else if value.Valid {
				_m.WindowEnd = new(time.Time)
				*_m.WindowEnd = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserRiskEvent.
// This includes values selected through modifiers, order, etc.
func (_m *UserRiskEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserRiskEvent entity.
func (_m *UserRiskEvent) QueryUser() *UserQuery {
	return NewUserRiskEventClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserRiskEvent.
// Note that you need to call UserRiskEvent.Unwrap() before calling this method if this UserRiskEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserRiskEvent) Update() *UserRiskEventUpdateOne {
	return NewUserRiskEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserRiskEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserRiskEvent) Unwrap() *UserRiskEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserRiskEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserRiskEvent) String() string {
	var builder strings.Builder
	builder.WriteString("UserRiskEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("score_delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScoreDelta))
	builder.WriteString(", ")
	builder.WriteString("score_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScoreAfter))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.WindowStart; v != nil {
		builder.WriteString("window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WindowEnd; v != nil {
		builder.WriteString("window_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserRiskEvents is a parsable slice of UserRiskEvent.
type UserRiskEvents []*UserRiskEvent
