// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userriskprofile"
)

// UserRiskProfileUpdate is the builder for updating UserRiskProfile entities.
type UserRiskProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserRiskProfileMutation
}

// Where appends a list predicates to the UserRiskProfileUpdate builder.
func (_u *UserRiskProfileUpdate) Where(ps ...predicate.UserRiskProfile) *UserRiskProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRiskProfileUpdate) SetUpdatedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRiskProfileUpdate) SetUserID(v int64) *UserRiskProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableUserID(v *int64) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *UserRiskProfileUpdate) SetScore(v float64) *UserRiskProfileUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableScore(v *float64) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *UserRiskProfileUpdate) AddScore(v float64) *UserRiskProfileUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserRiskProfileUpdate) SetStatus(v string) *UserRiskProfileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableStatus(v *string) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (_u *UserRiskProfileUpdate) SetConsecutiveBadDays(v int) *UserRiskProfileUpdate {
	_u.mutation.ResetConsecutiveBadDays()
	_u.mutation.SetConsecutiveBadDays(v)
	return _u
}

// SetNillableConsecutiveBadDays sets the "consecutive_bad_days" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableConsecutiveBadDays(v *int) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetConsecutiveBadDays(*v)
	}
	return _u
}

// AddConsecutiveBadDays adds value to the "consecutive_bad_days" field.
func (_u *UserRiskProfileUpdate) AddConsecutiveBadDays(v int) *UserRiskProfileUpdate {
	_u.mutation.AddConsecutiveBadDays(v)
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *UserRiskProfileUpdate) SetLastEvaluatedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableLastEvaluatedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *UserRiskProfileUpdate) ClearLastEvaluatedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (_u *UserRiskProfileUpdate) SetLastWarnedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetLastWarnedAt(v)
	return _u
}

// SetNillableLastWarnedAt sets the "last_warned_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableLastWarnedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetLastWarnedAt(*v)
	}
	return _u
}

// ClearLastWarnedAt clears the value of the "last_warned_at" field.
func (_u *UserRiskProfileUpdate) ClearLastWarnedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearLastWarnedAt()
	return _u
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (_u *UserRiskProfileUpdate) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetGracePeriodStartedAt(v)
	return _u
}

// SetNillableGracePeriodStartedAt sets the "grace_period_started_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableGracePeriodStartedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetGracePeriodStartedAt(*v)
	}
	return _u
}

// ClearGracePeriodStartedAt clears the value of the "grace_period_started_at" field.
func (_u *UserRiskProfileUpdate) ClearGracePeriodStartedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearGracePeriodStartedAt()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *UserRiskProfileUpdate) SetLockedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableLockedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *UserRiskProfileUpdate) ClearLockedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLockReason sets the "lock_reason" field.
func (_u *UserRiskProfileUpdate) SetLockReason(v string) *UserRiskProfileUpdate {
	_u.mutation.SetLockReason(v)
	return _u
}

// SetNillableLockReason sets the "lock_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableLockReason(v *string) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetLockReason(*v)
	}
	return _u
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (_u *UserRiskProfileUpdate) SetLastEvaluationSummary(v string) *UserRiskProfileUpdate {
	_u.mutation.SetLastEvaluationSummary(v)
	return _u
}

// SetNillableLastEvaluationSummary sets the "last_evaluation_summary" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableLastEvaluationSummary(v *string) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetLastEvaluationSummary(*v)
	}
	return _u
}

// SetExempted sets the "exempted" field.
func (_u *UserRiskProfileUpdate) SetExempted(v bool) *UserRiskProfileUpdate {
	_u.mutation.SetExempted(v)
	return _u
}

// SetNillableExempted sets the "exempted" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableExempted(v *bool) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetExempted(*v)
	}
	return _u
}

// SetExemptedAt sets the "exempted_at" field.
func (_u *UserRiskProfileUpdate) SetExemptedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetExemptedAt(v)
	return _u
}

// SetNillableExemptedAt sets the "exempted_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableExemptedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetExemptedAt(*v)
	}
	return _u
}

// ClearExemptedAt clears the value of the "exempted_at" field.
func (_u *UserRiskProfileUpdate) ClearExemptedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearExemptedAt()
	return _u
}

// SetExemptedBy sets the "exempted_by" field.
func (_u *UserRiskProfileUpdate) SetExemptedBy(v int64) *UserRiskProfileUpdate {
	_u.mutation.ResetExemptedBy()
	_u.mutation.SetExemptedBy(v)
	return _u
}

// SetNillableExemptedBy sets the "exempted_by" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableExemptedBy(v *int64) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetExemptedBy(*v)
	}
	return _u
}

// AddExemptedBy adds value to the "exempted_by" field.
func (_u *UserRiskProfileUpdate) AddExemptedBy(v int64) *UserRiskProfileUpdate {
	_u.mutation.AddExemptedBy(v)
	return _u
}

// ClearExemptedBy clears the value of the "exempted_by" field.
func (_u *UserRiskProfileUpdate) ClearExemptedBy() *UserRiskProfileUpdate {
	_u.mutation.ClearExemptedBy()
	return _u
}

// SetExemptionReason sets the "exemption_reason" field.
func (_u *UserRiskProfileUpdate) SetExemptionReason(v string) *UserRiskProfileUpdate {
	_u.mutation.SetExemptionReason(v)
	return _u
}

// SetNillableExemptionReason sets the "exemption_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableExemptionReason(v *string) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetExemptionReason(*v)
	}
	return _u
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_u *UserRiskProfileUpdate) SetUnlockedAt(v time.Time) *UserRiskProfileUpdate {
	_u.mutation.SetUnlockedAt(v)
	return _u
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableUnlockedAt(v *time.Time) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetUnlockedAt(*v)
	}
	return _u
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (_u *UserRiskProfileUpdate) ClearUnlockedAt() *UserRiskProfileUpdate {
	_u.mutation.ClearUnlockedAt()
	return _u
}

// SetUnlockedBy sets the "unlocked_by" field.
func (_u *UserRiskProfileUpdate) SetUnlockedBy(v int64) *UserRiskProfileUpdate {
	_u.mutation.ResetUnlockedBy()
	_u.mutation.SetUnlockedBy(v)
	return _u
}

// SetNillableUnlockedBy sets the "unlocked_by" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableUnlockedBy(v *int64) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetUnlockedBy(*v)
	}
	return _u
}

// AddUnlockedBy adds value to the "unlocked_by" field.
func (_u *UserRiskProfileUpdate) AddUnlockedBy(v int64) *UserRiskProfileUpdate {
	_u.mutation.AddUnlockedBy(v)
	return _u
}

// ClearUnlockedBy clears the value of the "unlocked_by" field.
func (_u *UserRiskProfileUpdate) ClearUnlockedBy() *UserRiskProfileUpdate {
	_u.mutation.ClearUnlockedBy()
	return _u
}

// SetUnlockReason sets the "unlock_reason" field.
func (_u *UserRiskProfileUpdate) SetUnlockReason(v string) *UserRiskProfileUpdate {
	_u.mutation.SetUnlockReason(v)
	return _u
}

// SetNillableUnlockReason sets the "unlock_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdate) SetNillableUnlockReason(v *string) *UserRiskProfileUpdate {
	if v != nil {
		_u.SetUnlockReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRiskProfileUpdate) SetUser(v *User) *UserRiskProfileUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRiskProfileMutation object of the builder.
func (_u *UserRiskProfileUpdate) Mutation() *UserRiskProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRiskProfileUpdate) ClearUser() *UserRiskProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRiskProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRiskProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRiskProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRiskProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRiskProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userriskprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRiskProfileUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := userriskprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRiskProfile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRiskProfile.user"`)
	}
	return nil
}

func (_u *UserRiskProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userriskprofile.Table, userriskprofile.Columns, sqlgraph.NewFieldSpec(userriskprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(userriskprofile.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(userriskprofile.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userriskprofile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveBadDays(); ok {
		_spec.SetField(userriskprofile.FieldConsecutiveBadDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveBadDays(); ok {
		_spec.AddField(userriskprofile.FieldConsecutiveBadDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastWarnedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastWarnedAt, field.TypeTime, value)
	}
	if _u.mutation.LastWarnedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLastWarnedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GracePeriodStartedAt(); ok {
		_spec.SetField(userriskprofile.FieldGracePeriodStartedAt, field.TypeTime, value)
	}
	if _u.mutation.GracePeriodStartedAtCleared() {
		_spec.ClearField(userriskprofile.FieldGracePeriodStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(userriskprofile.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockReason(); ok {
		_spec.SetField(userriskprofile.FieldLockReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastEvaluationSummary(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluationSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Exempted(); ok {
		_spec.SetField(userriskprofile.FieldExempted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExemptedAt(); ok {
		_spec.SetField(userriskprofile.FieldExemptedAt, field.TypeTime, value)
	}
	if _u.mutation.ExemptedAtCleared() {
		_spec.ClearField(userriskprofile.FieldExemptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExemptedBy(); ok {
		_spec.SetField(userriskprofile.FieldExemptedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExemptedBy(); ok {
		_spec.AddField(userriskprofile.FieldExemptedBy, field.TypeInt64, value)
	}
	if _u.mutation.ExemptedByCleared() {
		_spec.ClearField(userriskprofile.FieldExemptedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExemptionReason(); ok {
		_spec.SetField(userriskprofile.FieldExemptionReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnlockedAt(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedAt, field.TypeTime, value)
	}
	if _u.mutation.UnlockedAtCleared() {
		_spec.ClearField(userriskprofile.FieldUnlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnlockedBy(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnlockedBy(); ok {
		_spec.AddField(userriskprofile.FieldUnlockedBy, field.TypeInt64, value)
	}
	if _u.mutation.UnlockedByCleared() {
		_spec.ClearField(userriskprofile.FieldUnlockedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UnlockReason(); ok {
		_spec.SetField(userriskprofile.FieldUnlockReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userriskprofile.UserTable,
			Columns: []string{userriskprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userriskprofile.UserTable,
			Columns: []string{userriskprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userriskprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRiskProfileUpdateOne is the builder for updating a single UserRiskProfile entity.
type UserRiskProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRiskProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRiskProfileUpdateOne) SetUpdatedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRiskProfileUpdateOne) SetUserID(v int64) *UserRiskProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableUserID(v *int64) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *UserRiskProfileUpdateOne) SetScore(v float64) *UserRiskProfileUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableScore(v *float64) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *UserRiskProfileUpdateOne) AddScore(v float64) *UserRiskProfileUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserRiskProfileUpdateOne) SetStatus(v string) *UserRiskProfileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableStatus(v *string) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConsecutiveBadDays sets the "consecutive_bad_days" field.
func (_u *UserRiskProfileUpdateOne) SetConsecutiveBadDays(v int) *UserRiskProfileUpdateOne {
	_u.mutation.ResetConsecutiveBadDays()
	_u.mutation.SetConsecutiveBadDays(v)
	return _u
}

// SetNillableConsecutiveBadDays sets the "consecutive_bad_days" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableConsecutiveBadDays(v *int) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetConsecutiveBadDays(*v)
	}
	return _u
}

// AddConsecutiveBadDays adds value to the "consecutive_bad_days" field.
func (_u *UserRiskProfileUpdateOne) AddConsecutiveBadDays(v int) *UserRiskProfileUpdateOne {
	_u.mutation.AddConsecutiveBadDays(v)
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *UserRiskProfileUpdateOne) SetLastEvaluatedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableLastEvaluatedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *UserRiskProfileUpdateOne) ClearLastEvaluatedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastWarnedAt sets the "last_warned_at" field.
func (_u *UserRiskProfileUpdateOne) SetLastWarnedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetLastWarnedAt(v)
	return _u
}

// SetNillableLastWarnedAt sets the "last_warned_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableLastWarnedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetLastWarnedAt(*v)
	}
	return _u
}

// ClearLastWarnedAt clears the value of the "last_warned_at" field.
func (_u *UserRiskProfileUpdateOne) ClearLastWarnedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearLastWarnedAt()
	return _u
}

// SetGracePeriodStartedAt sets the "grace_period_started_at" field.
func (_u *UserRiskProfileUpdateOne) SetGracePeriodStartedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetGracePeriodStartedAt(v)
	return _u
}

// SetNillableGracePeriodStartedAt sets the "grace_period_started_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableGracePeriodStartedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetGracePeriodStartedAt(*v)
	}
	return _u
}

// ClearGracePeriodStartedAt clears the value of the "grace_period_started_at" field.
func (_u *UserRiskProfileUpdateOne) ClearGracePeriodStartedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearGracePeriodStartedAt()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *UserRiskProfileUpdateOne) SetLockedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableLockedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *UserRiskProfileUpdateOne) ClearLockedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLockReason sets the "lock_reason" field.
func (_u *UserRiskProfileUpdateOne) SetLockReason(v string) *UserRiskProfileUpdateOne {
	_u.mutation.SetLockReason(v)
	return _u
}

// SetNillableLockReason sets the "lock_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableLockReason(v *string) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetLockReason(*v)
	}
	return _u
}

// SetLastEvaluationSummary sets the "last_evaluation_summary" field.
func (_u *UserRiskProfileUpdateOne) SetLastEvaluationSummary(v string) *UserRiskProfileUpdateOne {
	_u.mutation.SetLastEvaluationSummary(v)
	return _u
}

// SetNillableLastEvaluationSummary sets the "last_evaluation_summary" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableLastEvaluationSummary(v *string) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetLastEvaluationSummary(*v)
	}
	return _u
}

// SetExempted sets the "exempted" field.
func (_u *UserRiskProfileUpdateOne) SetExempted(v bool) *UserRiskProfileUpdateOne {
	_u.mutation.SetExempted(v)
	return _u
}

// SetNillableExempted sets the "exempted" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableExempted(v *bool) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetExempted(*v)
	}
	return _u
}

// SetExemptedAt sets the "exempted_at" field.
func (_u *UserRiskProfileUpdateOne) SetExemptedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetExemptedAt(v)
	return _u
}

// SetNillableExemptedAt sets the "exempted_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableExemptedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetExemptedAt(*v)
	}
	return _u
}

// ClearExemptedAt clears the value of the "exempted_at" field.
func (_u *UserRiskProfileUpdateOne) ClearExemptedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearExemptedAt()
	return _u
}

// SetExemptedBy sets the "exempted_by" field.
func (_u *UserRiskProfileUpdateOne) SetExemptedBy(v int64) *UserRiskProfileUpdateOne {
	_u.mutation.ResetExemptedBy()
	_u.mutation.SetExemptedBy(v)
	return _u
}

// SetNillableExemptedBy sets the "exempted_by" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableExemptedBy(v *int64) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetExemptedBy(*v)
	}
	return _u
}

// AddExemptedBy adds value to the "exempted_by" field.
func (_u *UserRiskProfileUpdateOne) AddExemptedBy(v int64) *UserRiskProfileUpdateOne {
	_u.mutation.AddExemptedBy(v)
	return _u
}

// ClearExemptedBy clears the value of the "exempted_by" field.
func (_u *UserRiskProfileUpdateOne) ClearExemptedBy() *UserRiskProfileUpdateOne {
	_u.mutation.ClearExemptedBy()
	return _u
}

// SetExemptionReason sets the "exemption_reason" field.
func (_u *UserRiskProfileUpdateOne) SetExemptionReason(v string) *UserRiskProfileUpdateOne {
	_u.mutation.SetExemptionReason(v)
	return _u
}

// SetNillableExemptionReason sets the "exemption_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableExemptionReason(v *string) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetExemptionReason(*v)
	}
	return _u
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_u *UserRiskProfileUpdateOne) SetUnlockedAt(v time.Time) *UserRiskProfileUpdateOne {
	_u.mutation.SetUnlockedAt(v)
	return _u
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableUnlockedAt(v *time.Time) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetUnlockedAt(*v)
	}
	return _u
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (_u *UserRiskProfileUpdateOne) ClearUnlockedAt() *UserRiskProfileUpdateOne {
	_u.mutation.ClearUnlockedAt()
	return _u
}

// SetUnlockedBy sets the "unlocked_by" field.
func (_u *UserRiskProfileUpdateOne) SetUnlockedBy(v int64) *UserRiskProfileUpdateOne {
	_u.mutation.ResetUnlockedBy()
	_u.mutation.SetUnlockedBy(v)
	return _u
}

// SetNillableUnlockedBy sets the "unlocked_by" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableUnlockedBy(v *int64) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetUnlockedBy(*v)
	}
	return _u
}

// AddUnlockedBy adds value to the "unlocked_by" field.
func (_u *UserRiskProfileUpdateOne) AddUnlockedBy(v int64) *UserRiskProfileUpdateOne {
	_u.mutation.AddUnlockedBy(v)
	return _u
}

// ClearUnlockedBy clears the value of the "unlocked_by" field.
func (_u *UserRiskProfileUpdateOne) ClearUnlockedBy() *UserRiskProfileUpdateOne {
	_u.mutation.ClearUnlockedBy()
	return _u
}

// SetUnlockReason sets the "unlock_reason" field.
func (_u *UserRiskProfileUpdateOne) SetUnlockReason(v string) *UserRiskProfileUpdateOne {
	_u.mutation.SetUnlockReason(v)
	return _u
}

// SetNillableUnlockReason sets the "unlock_reason" field if the given value is not nil.
func (_u *UserRiskProfileUpdateOne) SetNillableUnlockReason(v *string) *UserRiskProfileUpdateOne {
	if v != nil {
		_u.SetUnlockReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRiskProfileUpdateOne) SetUser(v *User) *UserRiskProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRiskProfileMutation object of the builder.
func (_u *UserRiskProfileUpdateOne) Mutation() *UserRiskProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRiskProfileUpdateOne) ClearUser() *UserRiskProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserRiskProfileUpdate builder.
func (_u *UserRiskProfileUpdateOne) Where(ps ...predicate.UserRiskProfile) *UserRiskProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRiskProfileUpdateOne) Select(field string, fields ...string) *UserRiskProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRiskProfile entity.
func (_u *UserRiskProfileUpdateOne) Save(ctx context.Context) (*UserRiskProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRiskProfileUpdateOne) SaveX(ctx context.Context) *UserRiskProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRiskProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRiskProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRiskProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userriskprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRiskProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := userriskprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRiskProfile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRiskProfile.user"`)
	}
	return nil
}

func (_u *UserRiskProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserRiskProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userriskprofile.Table, userriskprofile.Columns, sqlgraph.NewFieldSpec(userriskprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRiskProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userriskprofile.FieldID)
		for _, f := range fields {
			if !userriskprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userriskprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userriskprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(userriskprofile.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(userriskprofile.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userriskprofile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveBadDays(); ok {
		_spec.SetField(userriskprofile.FieldConsecutiveBadDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveBadDays(); ok {
		_spec.AddField(userriskprofile.FieldConsecutiveBadDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastWarnedAt(); ok {
		_spec.SetField(userriskprofile.FieldLastWarnedAt, field.TypeTime, value)
	}
	if _u.mutation.LastWarnedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLastWarnedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GracePeriodStartedAt(); ok {
		_spec.SetField(userriskprofile.FieldGracePeriodStartedAt, field.TypeTime, value)
	}
	if _u.mutation.GracePeriodStartedAtCleared() {
		_spec.ClearField(userriskprofile.FieldGracePeriodStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(userriskprofile.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(userriskprofile.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockReason(); ok {
		_spec.SetField(userriskprofile.FieldLockReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastEvaluationSummary(); ok {
		_spec.SetField(userriskprofile.FieldLastEvaluationSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Exempted(); ok {
		_spec.SetField(userriskprofile.FieldExempted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExemptedAt(); ok {
		_spec.SetField(userriskprofile.FieldExemptedAt, field.TypeTime, value)
	}
	if _u.mutation.ExemptedAtCleared() {
		_spec.ClearField(userriskprofile.FieldExemptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExemptedBy(); ok {
		_spec.SetField(userriskprofile.FieldExemptedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExemptedBy(); ok {
		_spec.AddField(userriskprofile.FieldExemptedBy, field.TypeInt64, value)
	}
	if _u.mutation.ExemptedByCleared() {
		_spec.ClearField(userriskprofile.FieldExemptedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExemptionReason(); ok {
		_spec.SetField(userriskprofile.FieldExemptionReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnlockedAt(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedAt, field.TypeTime, value)
	}
	if _u.mutation.UnlockedAtCleared() {
		_spec.ClearField(userriskprofile.FieldUnlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnlockedBy(); ok {
		_spec.SetField(userriskprofile.FieldUnlockedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnlockedBy(); ok {
		_spec.AddField(userriskprofile.FieldUnlockedBy, field.TypeInt64, value)
	}
	if _u.mutation.UnlockedByCleared() {
		_spec.ClearField(userriskprofile.FieldUnlockedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UnlockReason(); ok {
		_spec.SetField(userriskprofile.FieldUnlockReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userriskprofile.UserTable,
			Columns: []string{userriskprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userriskprofile.UserTable,
			Columns: []string{userriskprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRiskProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userriskprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
