// Code generated by ent, DO NOT EDIT.

package userriskevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldUserID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldEventType, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldSeverity, v))
}

// ScoreDelta applies equality check predicate on the "score_delta" field. It's identical to ScoreDeltaEQ.
func ScoreDelta(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldScoreDelta, v))
}

// ScoreAfter applies equality check predicate on the "score_after" field. It's identical to ScoreAfterEQ.
func ScoreAfter(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldScoreAfter, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldSummary, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldWindowStart, v))
}

// WindowEnd applies equality check predicate on the "window_end" field. It's identical to WindowEndEQ.
func WindowEnd(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldWindowEnd, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContainsFold(FieldEventType, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// ScoreDeltaEQ applies the EQ predicate on the "score_delta" field.
func ScoreDeltaEQ(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldScoreDelta, v))
}

// ScoreDeltaNEQ applies the NEQ predicate on the "score_delta" field.
func ScoreDeltaNEQ(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldScoreDelta, v))
}

// ScoreDeltaIn applies the In predicate on the "score_delta" field.
func ScoreDeltaIn(vs ...float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldScoreDelta, vs...))
}

// ScoreDeltaNotIn applies the NotIn predicate on the "score_delta" field.
func ScoreDeltaNotIn(vs ...float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldScoreDelta, vs...))
}

// ScoreDeltaGT applies the GT predicate on the "score_delta" field.
func ScoreDeltaGT(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldScoreDelta, v))
}

// ScoreDeltaGTE applies the GTE predicate on the "score_delta" field.
func ScoreDeltaGTE(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldScoreDelta, v))
}

// ScoreDeltaLT applies the LT predicate on the "score_delta" field.
func ScoreDeltaLT(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldScoreDelta, v))
}

// ScoreDeltaLTE applies the LTE predicate on the "score_delta" field.
func ScoreDeltaLTE(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldScoreDelta, v))
}

// ScoreAfterEQ applies the EQ predicate on the "score_after" field.
func ScoreAfterEQ(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldScoreAfter, v))
}

// ScoreAfterNEQ applies the NEQ predicate on the "score_after" field.
func ScoreAfterNEQ(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldScoreAfter, v))
}

// ScoreAfterIn applies the In predicate on the "score_after" field.
func ScoreAfterIn(vs ...float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldScoreAfter, vs...))
}

// ScoreAfterNotIn applies the NotIn predicate on the "score_after" field.
func ScoreAfterNotIn(vs ...float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldScoreAfter, vs...))
}

// ScoreAfterGT applies the GT predicate on the "score_after" field.
func ScoreAfterGT(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldScoreAfter, v))
}

// ScoreAfterGTE applies the GTE predicate on the "score_after" field.
func ScoreAfterGTE(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldScoreAfter, v))
}

// ScoreAfterLT applies the LT predicate on the "score_after" field.
func ScoreAfterLT(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldScoreAfter, v))
}

// ScoreAfterLTE applies the LTE predicate on the "score_after" field.
func ScoreAfterLTE(v float64) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldScoreAfter, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldContainsFold(FieldSummary, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotNull(FieldMetadata))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldWindowStart, v))
}

// WindowStartIsNil applies the IsNil predicate on the "window_start" field.
func WindowStartIsNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIsNull(FieldWindowStart))
}

// WindowStartNotNil applies the NotNil predicate on the "window_start" field.
func WindowStartNotNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotNull(FieldWindowStart))
}

// WindowEndEQ applies the EQ predicate on the "window_end" field.
func WindowEndEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldEQ(FieldWindowEnd, v))
}

// WindowEndNEQ applies the NEQ predicate on the "window_end" field.
func WindowEndNEQ(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNEQ(FieldWindowEnd, v))
}

// WindowEndIn applies the In predicate on the "window_end" field.
func WindowEndIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIn(FieldWindowEnd, vs...))
}

// WindowEndNotIn applies the NotIn predicate on the "window_end" field.
func WindowEndNotIn(vs ...time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotIn(FieldWindowEnd, vs...))
}

// WindowEndGT applies the GT predicate on the "window_end" field.
func WindowEndGT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGT(FieldWindowEnd, v))
}

// WindowEndGTE applies the GTE predicate on the "window_end" field.
func WindowEndGTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldGTE(FieldWindowEnd, v))
}

// WindowEndLT applies the LT predicate on the "window_end" field.
func WindowEndLT(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLT(FieldWindowEnd, v))
}

// WindowEndLTE applies the LTE predicate on the "window_end" field.
func WindowEndLTE(v time.Time) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldLTE(FieldWindowEnd, v))
}

// WindowEndIsNil applies the IsNil predicate on the "window_end" field.
func WindowEndIsNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldIsNull(FieldWindowEnd))
}

// WindowEndNotNil applies the NotNil predicate on the "window_end" field.
func WindowEndNotNil() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.FieldNotNull(FieldWindowEnd))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserRiskEvent {
	return predicate.UserRiskEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRiskEvent) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRiskEvent) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRiskEvent) predicate.UserRiskEvent {
	return predicate.UserRiskEvent(sql.NotPredicates(p))
}
